// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pricing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateFeeRequest) Reset() {
	*x = CalculateFeeRequest{}
	mi := &file_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeRequest) ProtoMessage() {}

func (x *CalculateFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeRequest.ProtoReflect.Descriptor instead.
func (*CalculateFeeRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateFeeRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CalculateFeeRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CalculateFeeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculateFeeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CalculateFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalFee      int64                  `protobuf:"varint,1,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PlatformCut   int64                  `protobuf:"varint,2,opt,name=platform_cut,json=platformCut,proto3" json:"platform_cut,omitempty"`
	MerchantCut   int64                  `protobuf:"varint,3,opt,name=merchant_cut,json=merchantCut,proto3" json:"merchant_cut,omitempty"`
	AppliedRules  []string               `protobuf:"bytes,4,rep,name=applied_rules,json=appliedRules,proto3" json:"applied_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateFeeResponse) Reset() {
	*x = CalculateFeeResponse{}
	mi := &file_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeResponse) ProtoMessage() {}

func (x *CalculateFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeResponse.ProtoReflect.Descriptor instead.
func (*CalculateFeeResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateFeeResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *CalculateFeeResponse) GetPlatformCut() int64 {
	if x != nil {
		return x.PlatformCut
	}
	return 0
}

func (x *CalculateFeeResponse) GetMerchantCut() int64 {
	if x != nil {
		return x.MerchantCut
	}
	return 0
}

func (x *CalculateFeeResponse) GetAppliedRules() []string {
	if x != nil {
		return x.AppliedRules
	}
	return nil
}

var File_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_rawDesc = "" +
	"\n" +
	"\rpricing.proto\x12\n" +
	"pricing.v1\"\x91\x01\n" +
	"\x13CalculateFeeRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\x9e\x01\n" +
	"\x14CalculateFeeResponse\x12\x1b\n" +
	"\ttotal_fee\x18\x01 \x01(\x03R\btotalFee\x12!\n" +
	"\fplatform_cut\x18\x02 \x01(\x03R\vplatformCut\x12!\n" +
	"\fmerchant_cut\x18\x03 \x01(\x03R\vmerchantCut\x12#\n" +
	"\rapplied_rules\x18\x04 \x03(\tR\fappliedRules2c\n" +
	"\x0ePricingService\x12Q\n" +
	"\fCalculateFee\x12\x1f.pricing.v1.CalculateFeeRequest\x1a .pricing.v1.CalculateFeeResponseB$Z\"payment-gateway/pricing-service/pbb\x06proto3"

var (
	file_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_rawDescData []byte
)

func file_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_rawDescData
}

var file_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pricing_proto_goTypes = []any{
	(*CalculateFeeRequest)(nil),  // 0: pricing.v1.CalculateFeeRequest
	(*CalculateFeeResponse)(nil), // 1: pricing.v1.CalculateFeeResponse
}
var file_pricing_proto_depIdxs = []int32{
	0, // 0: pricing.v1.PricingService.CalculateFee:input_type -> pricing.v1.CalculateFeeRequest
	1, // 1: pricing.v1.PricingService.CalculateFee:output_type -> pricing.v1.CalculateFeeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pricing_proto_init() }
func file_pricing_proto_init() {
	if File_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto = out.File
	file_pricing_proto_goTypes = nil
	file_pricing_proto_depIdxs = nil
}
