version: '3.8'
networks:
  payment_network:
    driver: bridge

volumes:
  postgres_data: null
  redis_data: null
  kafka_data: null
  prometheus_data: null
  grafana_data: null

services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: payment_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - payment_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: payment_kafka
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - payment_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 10

  kafka-init:
    image: apache/kafka:latest
    container_name: payment_kafka_init
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - payment_network
    command: >
      bash -c "
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --topic payment.events &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --topic webhook.events &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic merchant.events &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --topic transaction.status.updated
      "

  mailhog:
    image: mailhog/mailhog:latest
    container_name: payment_gateway_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - payment_network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8765:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - payment_network

  nginx_local:
    image: nginx:1.25-alpine
    container_name: payment_gateway_local
    restart: always
    network_mode: "host"
    volumes:
      - ./infra/nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: payment_jaeger
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC default port
      - "4318:4318"   # OTLP HTTP default port
    networks:
      - payment_network

  prometheus:
    image: prom/prometheus:latest
    container_name: payment_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - payment_network
