[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:nginx]
command=/bin/sh -c "sed -i \"s/listen 8080;/listen ${PORT:-8080};/g\" /etc/nginx/nginx.conf && /usr/sbin/nginx -g \"daemon off;\""
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:auth-service]
directory=/app/services/auth-service
command=npm run start
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:merchant-service]
directory=/app/services/merchant-service
command=npm run start
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:payment-service]
command=/app/bin/payment-service
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ledger-service]
command=/app/bin/ledger-service
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:transaction-service]
command=/app/bin/transaction-service
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:provider-service]
command=/app/bin/provider-service
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:webhook-service]
command=/app/bin/webhook-service
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dashboard-service]
directory=/app/services/dashboard-service
command=npm run start
autostart=true
autorestart=true
environment=PORT=""
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
