// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: risk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CustomerId    string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRiskRequest) Reset() {
	*x = CheckRiskRequest{}
	mi := &file_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRiskRequest) ProtoMessage() {}

func (x *CheckRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRiskRequest.ProtoReflect.Descriptor instead.
func (*CheckRiskRequest) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRiskRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CheckRiskRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CheckRiskRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CheckRiskRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CheckRiskRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CheckRiskRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CheckRiskRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CheckRiskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DecisionId       string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Action           string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // ALLOW, FLAG, REVIEW, BLOCK, CHALLENGE
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TriggeredRuleIds []string               `protobuf:"bytes,4,rep,name=triggered_rule_ids,json=triggeredRuleIds,proto3" json:"triggered_rule_ids,omitempty"`
	EvaluationStatus string                 `protobuf:"bytes,5,opt,name=evaluation_status,json=evaluationStatus,proto3" json:"evaluation_status,omitempty"` // SUCCESS, UNAVAILABLE, TIMEOUT, ERROR
	RiskScore        float32                `protobuf:"fixed32,6,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`                    // ML Probability score (0.0 to 1.0)
	Requires_3Ds     bool                   `protobuf:"varint,7,opt,name=requires_3ds,json=requires3ds,proto3" json:"requires_3ds,omitempty"`               // Strong Customer Authentication flag
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckRiskResponse) Reset() {
	*x = CheckRiskResponse{}
	mi := &file_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRiskResponse) ProtoMessage() {}

func (x *CheckRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRiskResponse.ProtoReflect.Descriptor instead.
func (*CheckRiskResponse) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRiskResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CheckRiskResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRiskResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckRiskResponse) GetTriggeredRuleIds() []string {
	if x != nil {
		return x.TriggeredRuleIds
	}
	return nil
}

func (x *CheckRiskResponse) GetEvaluationStatus() string {
	if x != nil {
		return x.EvaluationStatus
	}
	return ""
}

func (x *CheckRiskResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *CheckRiskResponse) GetRequires_3Ds() bool {
	if x != nil {
		return x.Requires_3Ds
	}
	return false
}

var File_risk_proto protoreflect.FileDescriptor

const file_risk_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"risk.proto\x12\x04risk\"\xed\x01\n" +
	"\x10CheckRiskRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\"\x81\x02\n" +
	"\x11CheckRiskResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12,\n" +
	"\x12triggered_rule_ids\x18\x04 \x03(\tR\x10triggeredRuleIds\x12+\n" +
	"\x11evaluation_status\x18\x05 \x01(\tR\x10evaluationStatus\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x06 \x01(\x02R\triskScore\x12!\n" +
	"\frequires_3ds\x18\a \x01(\bR\vrequires3ds2K\n" +
	"\vRiskService\x12<\n" +
	"\tCheckRisk\x12\x16.risk.CheckRiskRequest\x1a\x17.risk.CheckRiskResponseB-Z+payment-gateway/services/risk-service/protob\x06proto3"

var (
	file_risk_proto_rawDescOnce sync.Once
	file_risk_proto_rawDescData []byte
)

func file_risk_proto_rawDescGZIP() []byte {
	file_risk_proto_rawDescOnce.Do(func() {
		file_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_risk_proto_rawDesc), len(file_risk_proto_rawDesc)))
	})
	return file_risk_proto_rawDescData
}

var file_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_risk_proto_goTypes = []any{
	(*CheckRiskRequest)(nil),  // 0: risk.CheckRiskRequest
	(*CheckRiskResponse)(nil), // 1: risk.CheckRiskResponse
}
var file_risk_proto_depIdxs = []int32{
	0, // 0: risk.RiskService.CheckRisk:input_type -> risk.CheckRiskRequest
	1, // 1: risk.RiskService.CheckRisk:output_type -> risk.CheckRiskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_risk_proto_init() }
func file_risk_proto_init() {
	if File_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_risk_proto_rawDesc), len(file_risk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_proto_goTypes,
		DependencyIndexes: file_risk_proto_depIdxs,
		MessageInfos:      file_risk_proto_msgTypes,
	}.Build()
	File_risk_proto = out.File
	file_risk_proto_goTypes = nil
	file_risk_proto_depIdxs = nil
}
