// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: context.proto

package grpccontext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectId      string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`    // Human user ID (if any)
	MerchantId     string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Tenant boundary
	Roles          []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions    []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	SessionId      string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AuthType       string                 `protobuf:"bytes,6,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`                // "USER", "SERVICE", "SYSTEM"
	CallerService  string                 `protobuf:"bytes,7,opt,name=caller_service,json=callerService,proto3" json:"caller_service,omitempty"` // The SPIFFE identity that initiated this specific RPC
	ContextVersion int32                  `protobuf:"varint,8,opt,name=context_version,json=contextVersion,proto3" json:"context_version,omitempty"`
	Environment    string                 `protobuf:"bytes,9,opt,name=environment,proto3" json:"environment,omitempty"` // 'TEST' or 'LIVE'
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RequestContext) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RequestContext) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RequestContext) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RequestContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestContext) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *RequestContext) GetCallerService() string {
	if x != nil {
		return x.CallerService
	}
	return ""
}

func (x *RequestContext) GetContextVersion() int32 {
	if x != nil {
		return x.ContextVersion
	}
	return 0
}

func (x *RequestContext) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

var File_context_proto protoreflect.FileDescriptor

const file_context_proto_rawDesc = "" +
	"\n" +
	"\rcontext.proto\x12\acontext\"\xb6\x02\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tauth_type\x18\x06 \x01(\tR\bauthType\x12%\n" +
	"\x0ecaller_service\x18\a \x01(\tR\rcallerService\x12'\n" +
	"\x0fcontext_version\x18\b \x01(\x05R\x0econtextVersion\x12 \n" +
	"\venvironment\x18\t \x01(\tR\venvironmentB0Z.payment-gateway/go-grpc-auth/proto;grpccontextb\x06proto3"

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData []byte
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)))
	})
	return file_context_proto_rawDescData
}

var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_context_proto_goTypes = []any{
	(*RequestContext)(nil), // 0: context.RequestContext
}
var file_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
