// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: vault.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenizeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`                           // Raw 16-19 digit card number
	ExpMonth      string                 `protobuf:"bytes,2,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"` // MM
	ExpYear       string                 `protobuf:"bytes,3,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`    // YYYY or YY
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`                           // Optional for vaulting, usually required for immediate charge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenizeCardRequest) Reset() {
	*x = TokenizeCardRequest{}
	mi := &file_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeCardRequest) ProtoMessage() {}

func (x *TokenizeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeCardRequest.ProtoReflect.Descriptor instead.
func (*TokenizeCardRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{0}
}

func (x *TokenizeCardRequest) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *TokenizeCardRequest) GetExpMonth() string {
	if x != nil {
		return x.ExpMonth
	}
	return ""
}

func (x *TokenizeCardRequest) GetExpYear() string {
	if x != nil {
		return x.ExpYear
	}
	return ""
}

func (x *TokenizeCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

type TokenizeCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Safe token string, e.g., tok_...
	Last4         string                 `protobuf:"bytes,2,opt,name=last4,proto3" json:"last4,omitempty"` // Last 4 digits for display purposes
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"` // Card brand (visa, mastercard, etc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenizeCardResponse) Reset() {
	*x = TokenizeCardResponse{}
	mi := &file_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizeCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeCardResponse) ProtoMessage() {}

func (x *TokenizeCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeCardResponse.ProtoReflect.Descriptor instead.
func (*TokenizeCardResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{1}
}

func (x *TokenizeCardResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenizeCardResponse) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *TokenizeCardResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type DetokenizeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetokenizeCardRequest) Reset() {
	*x = DetokenizeCardRequest{}
	mi := &file_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetokenizeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetokenizeCardRequest) ProtoMessage() {}

func (x *DetokenizeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetokenizeCardRequest.ProtoReflect.Descriptor instead.
func (*DetokenizeCardRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{2}
}

func (x *DetokenizeCardRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DetokenizeCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`
	ExpMonth      string                 `protobuf:"bytes,2,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       string                 `protobuf:"bytes,3,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetokenizeCardResponse) Reset() {
	*x = DetokenizeCardResponse{}
	mi := &file_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetokenizeCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetokenizeCardResponse) ProtoMessage() {}

func (x *DetokenizeCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetokenizeCardResponse.ProtoReflect.Descriptor instead.
func (*DetokenizeCardResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{3}
}

func (x *DetokenizeCardResponse) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *DetokenizeCardResponse) GetExpMonth() string {
	if x != nil {
		return x.ExpMonth
	}
	return ""
}

func (x *DetokenizeCardResponse) GetExpYear() string {
	if x != nil {
		return x.ExpYear
	}
	return ""
}

func (x *DetokenizeCardResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

var File_vault_proto protoreflect.FileDescriptor

const file_vault_proto_rawDesc = "" +
	"\n" +
	"\vvault.proto\x12\x05vault\"q\n" +
	"\x13TokenizeCardRequest\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12\x1b\n" +
	"\texp_month\x18\x02 \x01(\tR\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x03 \x01(\tR\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\"X\n" +
	"\x14TokenizeCardResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05last4\x18\x02 \x01(\tR\x05last4\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\"-\n" +
	"\x15DetokenizeCardRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"t\n" +
	"\x16DetokenizeCardResponse\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12\x1b\n" +
	"\texp_month\x18\x02 \x01(\tR\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x03 \x01(\tR\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv2\xa6\x01\n" +
	"\fVaultService\x12G\n" +
	"\fTokenizeCard\x12\x1a.vault.TokenizeCardRequest\x1a\x1b.vault.TokenizeCardResponse\x12M\n" +
	"\x0eDetokenizeCard\x12\x1c.vault.DetokenizeCardRequest\x1a\x1d.vault.DetokenizeCardResponseB4Z2payment-gateway/services/vault-service/proto;vaultb\x06proto3"

var (
	file_vault_proto_rawDescOnce sync.Once
	file_vault_proto_rawDescData []byte
)

func file_vault_proto_rawDescGZIP() []byte {
	file_vault_proto_rawDescOnce.Do(func() {
		file_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)))
	})
	return file_vault_proto_rawDescData
}

var file_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vault_proto_goTypes = []any{
	(*TokenizeCardRequest)(nil),    // 0: vault.TokenizeCardRequest
	(*TokenizeCardResponse)(nil),   // 1: vault.TokenizeCardResponse
	(*DetokenizeCardRequest)(nil),  // 2: vault.DetokenizeCardRequest
	(*DetokenizeCardResponse)(nil), // 3: vault.DetokenizeCardResponse
}
var file_vault_proto_depIdxs = []int32{
	0, // 0: vault.VaultService.TokenizeCard:input_type -> vault.TokenizeCardRequest
	2, // 1: vault.VaultService.DetokenizeCard:input_type -> vault.DetokenizeCardRequest
	1, // 2: vault.VaultService.TokenizeCard:output_type -> vault.TokenizeCardResponse
	3, // 3: vault.VaultService.DetokenizeCard:output_type -> vault.DetokenizeCardResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vault_proto_init() }
func file_vault_proto_init() {
	if File_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_proto_goTypes,
		DependencyIndexes: file_vault_proto_depIdxs,
		MessageInfos:      file_vault_proto_msgTypes,
	}.Build()
	File_vault_proto = out.File
	file_vault_proto_goTypes = nil
	file_vault_proto_depIdxs = nil
}
