// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: vault.proto

package vault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultService_TokenizeCard_FullMethodName   = "/vault.VaultService/TokenizeCard"
	VaultService_DetokenizeCard_FullMethodName = "/vault.VaultService/DetokenizeCard"
)

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The VaultService is a highly isolated PCI-DSS Level 1 compliant enclave.
// Its sole purpose is to securely tokenize raw Primary Account Numbers (PAN)
// using envelope encryption (KMS) and detokenize them only for authorized internal callers.
type VaultServiceClient interface {
	// TokenizeCard accepts raw card data and returns a safe token (e.g. tok_123)
	TokenizeCard(ctx context.Context, in *TokenizeCardRequest, opts ...grpc.CallOption) (*TokenizeCardResponse, error)
	// DetokenizeCard accepts a token and returns the raw PAN.
	// Restricted strictly to ProviderService for dispatching to acquiring banks.
	DetokenizeCard(ctx context.Context, in *DetokenizeCardRequest, opts ...grpc.CallOption) (*DetokenizeCardResponse, error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) TokenizeCard(ctx context.Context, in *TokenizeCardRequest, opts ...grpc.CallOption) (*TokenizeCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeCardResponse)
	err := c.cc.Invoke(ctx, VaultService_TokenizeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) DetokenizeCard(ctx context.Context, in *DetokenizeCardRequest, opts ...grpc.CallOption) (*DetokenizeCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetokenizeCardResponse)
	err := c.cc.Invoke(ctx, VaultService_DetokenizeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
// All implementations must embed UnimplementedVaultServiceServer
// for forward compatibility.
//
// The VaultService is a highly isolated PCI-DSS Level 1 compliant enclave.
// Its sole purpose is to securely tokenize raw Primary Account Numbers (PAN)
// using envelope encryption (KMS) and detokenize them only for authorized internal callers.
type VaultServiceServer interface {
	// TokenizeCard accepts raw card data and returns a safe token (e.g. tok_123)
	TokenizeCard(context.Context, *TokenizeCardRequest) (*TokenizeCardResponse, error)
	// DetokenizeCard accepts a token and returns the raw PAN.
	// Restricted strictly to ProviderService for dispatching to acquiring banks.
	DetokenizeCard(context.Context, *DetokenizeCardRequest) (*DetokenizeCardResponse, error)
	mustEmbedUnimplementedVaultServiceServer()
}

// UnimplementedVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultServiceServer struct{}

func (UnimplementedVaultServiceServer) TokenizeCard(context.Context, *TokenizeCardRequest) (*TokenizeCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TokenizeCard not implemented")
}
func (UnimplementedVaultServiceServer) DetokenizeCard(context.Context, *DetokenizeCardRequest) (*DetokenizeCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetokenizeCard not implemented")
}
func (UnimplementedVaultServiceServer) mustEmbedUnimplementedVaultServiceServer() {}
func (UnimplementedVaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	// If the following call panics, it indicates UnimplementedVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_TokenizeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).TokenizeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_TokenizeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).TokenizeCard(ctx, req.(*TokenizeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_DetokenizeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetokenizeCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).DetokenizeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_DetokenizeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).DetokenizeCard(ctx, req.(*DetokenizeCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenizeCard",
			Handler:    _VaultService_TokenizeCard_Handler,
		},
		{
			MethodName: "DetokenizeCard",
			Handler:    _VaultService_DetokenizeCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}
