// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: provider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatusRequest) Reset() {
	*x = ProviderStatusRequest{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatusRequest) ProtoMessage() {}

func (x *ProviderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatusRequest.ProtoReflect.Descriptor instead.
func (*ProviderStatusRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderStatusRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type ProviderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatusResponse) Reset() {
	*x = ProviderStatusResponse{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatusResponse) ProtoMessage() {}

func (x *ProviderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatusResponse.ProtoReflect.Descriptor instead.
func (*ProviderStatusResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderStatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProviderStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitiatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *InitiatePaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiatePaymentRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type InitiatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // SUCCESS, PENDING, FAILED, TIMEOUT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentResponse) Reset() {
	*x = InitiatePaymentResponse{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentResponse) ProtoMessage() {}

func (x *InitiatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *InitiatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type InitiateRefundRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RefundId           string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	ProviderId         string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Amount             int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	OriginalProviderId *string                `protobuf:"bytes,5,opt,name=original_provider_id,json=originalProviderId,proto3,oneof" json:"original_provider_id,omitempty"`
	Environment        string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitiateRefundRequest) Reset() {
	*x = InitiateRefundRequest{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRefundRequest) ProtoMessage() {}

func (x *InitiateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRefundRequest.ProtoReflect.Descriptor instead.
func (*InitiateRefundRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *InitiateRefundRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *InitiateRefundRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *InitiateRefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiateRefundRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiateRefundRequest) GetOriginalProviderId() string {
	if x != nil && x.OriginalProviderId != nil {
		return *x.OriginalProviderId
	}
	return ""
}

func (x *InitiateRefundRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type InitiateRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // SUCCESS, PENDING, FAILED, TIMEOUT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateRefundResponse) Reset() {
	*x = InitiateRefundResponse{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRefundResponse) ProtoMessage() {}

func (x *InitiateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRefundResponse.ProtoReflect.Descriptor instead.
func (*InitiateRefundResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *InitiateRefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\bprovider\"8\n" +
	"\x15ProviderStatusRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"K\n" +
	"\x16ProviderStatusResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xae\x01\n" +
	"\x16InitiatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\"1\n" +
	"\x17InitiatePaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xfb\x01\n" +
	"\x15InitiateRefundRequest\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x125\n" +
	"\x14original_provider_id\x18\x05 \x01(\tH\x00R\x12originalProviderId\x88\x01\x01\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironmentB\x17\n" +
	"\x15_original_provider_id\"0\n" +
	"\x16InitiateRefundResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x96\x02\n" +
	"\x0fProviderService\x12V\n" +
	"\x11GetProviderStatus\x12\x1f.provider.ProviderStatusRequest\x1a .provider.ProviderStatusResponse\x12V\n" +
	"\x0fInitiatePayment\x12 .provider.InitiatePaymentRequest\x1a!.provider.InitiatePaymentResponse\x12S\n" +
	"\x0eInitiateRefund\x12\x1f.provider.InitiateRefundRequest\x1a .provider.InitiateRefundResponseB(Z&payment-gateway/provider-service/protob\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_provider_proto_goTypes = []any{
	(*ProviderStatusRequest)(nil),   // 0: provider.ProviderStatusRequest
	(*ProviderStatusResponse)(nil),  // 1: provider.ProviderStatusResponse
	(*InitiatePaymentRequest)(nil),  // 2: provider.InitiatePaymentRequest
	(*InitiatePaymentResponse)(nil), // 3: provider.InitiatePaymentResponse
	(*InitiateRefundRequest)(nil),   // 4: provider.InitiateRefundRequest
	(*InitiateRefundResponse)(nil),  // 5: provider.InitiateRefundResponse
}
var file_provider_proto_depIdxs = []int32{
	0, // 0: provider.ProviderService.GetProviderStatus:input_type -> provider.ProviderStatusRequest
	2, // 1: provider.ProviderService.InitiatePayment:input_type -> provider.InitiatePaymentRequest
	4, // 2: provider.ProviderService.InitiateRefund:input_type -> provider.InitiateRefundRequest
	1, // 3: provider.ProviderService.GetProviderStatus:output_type -> provider.ProviderStatusResponse
	3, // 4: provider.ProviderService.InitiatePayment:output_type -> provider.InitiatePaymentResponse
	5, // 5: provider.ProviderService.InitiateRefund:output_type -> provider.InitiateRefundResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	file_provider_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
