// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: webhook_read.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookReadService_GetWebhookDeliveries_FullMethodName = "/webhook_read.WebhookReadService/GetWebhookDeliveries"
)

// WebhookReadServiceClient is the client API for WebhookReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookReadServiceClient interface {
	GetWebhookDeliveries(ctx context.Context, in *GetWebhookDeliveriesRequest, opts ...grpc.CallOption) (*GetWebhookDeliveriesResponse, error)
}

type webhookReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookReadServiceClient(cc grpc.ClientConnInterface) WebhookReadServiceClient {
	return &webhookReadServiceClient{cc}
}

func (c *webhookReadServiceClient) GetWebhookDeliveries(ctx context.Context, in *GetWebhookDeliveriesRequest, opts ...grpc.CallOption) (*GetWebhookDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookDeliveriesResponse)
	err := c.cc.Invoke(ctx, WebhookReadService_GetWebhookDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookReadServiceServer is the server API for WebhookReadService service.
// All implementations must embed UnimplementedWebhookReadServiceServer
// for forward compatibility.
type WebhookReadServiceServer interface {
	GetWebhookDeliveries(context.Context, *GetWebhookDeliveriesRequest) (*GetWebhookDeliveriesResponse, error)
	mustEmbedUnimplementedWebhookReadServiceServer()
}

// UnimplementedWebhookReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookReadServiceServer struct{}

func (UnimplementedWebhookReadServiceServer) GetWebhookDeliveries(context.Context, *GetWebhookDeliveriesRequest) (*GetWebhookDeliveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookDeliveries not implemented")
}
func (UnimplementedWebhookReadServiceServer) mustEmbedUnimplementedWebhookReadServiceServer() {}
func (UnimplementedWebhookReadServiceServer) testEmbeddedByValue()                            {}

// UnsafeWebhookReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookReadServiceServer will
// result in compilation errors.
type UnsafeWebhookReadServiceServer interface {
	mustEmbedUnimplementedWebhookReadServiceServer()
}

func RegisterWebhookReadServiceServer(s grpc.ServiceRegistrar, srv WebhookReadServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookReadService_ServiceDesc, srv)
}

func _WebhookReadService_GetWebhookDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookReadServiceServer).GetWebhookDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookReadService_GetWebhookDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookReadServiceServer).GetWebhookDeliveries(ctx, req.(*GetWebhookDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookReadService_ServiceDesc is the grpc.ServiceDesc for WebhookReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webhook_read.WebhookReadService",
	HandlerType: (*WebhookReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWebhookDeliveries",
			Handler:    _WebhookReadService_GetWebhookDeliveries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webhook_read.proto",
}
