// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: merchant.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantService_GetMerchant_FullMethodName          = "/merchant.MerchantService/GetMerchant"
	MerchantService_GetMerchantStatus_FullMethodName    = "/merchant.MerchantService/GetMerchantStatus"
	MerchantService_ValidateApiKey_FullMethodName       = "/merchant.MerchantService/ValidateApiKey"
	MerchantService_GetMerchantConfig_FullMethodName    = "/merchant.MerchantService/GetMerchantConfig"
	MerchantService_GetWebhookConfig_FullMethodName     = "/merchant.MerchantService/GetWebhookConfig"
	MerchantService_GetPayoutDestination_FullMethodName = "/merchant.MerchantService/GetPayoutDestination"
	MerchantService_ListMerchants_FullMethodName        = "/merchant.MerchantService/ListMerchants"
	MerchantService_SuspendMerchant_FullMethodName      = "/merchant.MerchantService/SuspendMerchant"
	MerchantService_UpdateMerchantLimit_FullMethodName  = "/merchant.MerchantService/UpdateMerchantLimit"
	MerchantService_ProvisionMerchant_FullMethodName    = "/merchant.MerchantService/ProvisionMerchant"
)

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantServiceClient interface {
	GetMerchant(ctx context.Context, in *GetMerchantRequest, opts ...grpc.CallOption) (*GetMerchantResponse, error)
	GetMerchantStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error)
	GetMerchantConfig(ctx context.Context, in *GetMerchantConfigRequest, opts ...grpc.CallOption) (*GetMerchantConfigResponse, error)
	GetWebhookConfig(ctx context.Context, in *GetWebhookConfigRequest, opts ...grpc.CallOption) (*GetWebhookConfigResponse, error)
	GetPayoutDestination(ctx context.Context, in *GetPayoutDestinationRequest, opts ...grpc.CallOption) (*GetPayoutDestinationResponse, error)
	// Admin endpoints
	ListMerchants(ctx context.Context, in *ListMerchantsRequest, opts ...grpc.CallOption) (*ListMerchantsResponse, error)
	SuspendMerchant(ctx context.Context, in *SuspendMerchantRequest, opts ...grpc.CallOption) (*SuspendMerchantResponse, error)
	UpdateMerchantLimit(ctx context.Context, in *UpdateMerchantLimitRequest, opts ...grpc.CallOption) (*UpdateMerchantLimitResponse, error)
	// Provisioning
	ProvisionMerchant(ctx context.Context, in *ProvisionMerchantRequest, opts ...grpc.CallOption) (*ProvisionMerchantResponse, error)
}

type merchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantServiceClient(cc grpc.ClientConnInterface) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) GetMerchant(ctx context.Context, in *GetMerchantRequest, opts ...grpc.CallOption) (*GetMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchantStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateApiKeyResponse)
	err := c.cc.Invoke(ctx, MerchantService_ValidateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchantConfig(ctx context.Context, in *GetMerchantConfigRequest, opts ...grpc.CallOption) (*GetMerchantConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantConfigResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchantConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetWebhookConfig(ctx context.Context, in *GetWebhookConfigRequest, opts ...grpc.CallOption) (*GetWebhookConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookConfigResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetWebhookConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetPayoutDestination(ctx context.Context, in *GetPayoutDestinationRequest, opts ...grpc.CallOption) (*GetPayoutDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayoutDestinationResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetPayoutDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ListMerchants(ctx context.Context, in *ListMerchantsRequest, opts ...grpc.CallOption) (*ListMerchantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantsResponse)
	err := c.cc.Invoke(ctx, MerchantService_ListMerchants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) SuspendMerchant(ctx context.Context, in *SuspendMerchantRequest, opts ...grpc.CallOption) (*SuspendMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_SuspendMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) UpdateMerchantLimit(ctx context.Context, in *UpdateMerchantLimitRequest, opts ...grpc.CallOption) (*UpdateMerchantLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMerchantLimitResponse)
	err := c.cc.Invoke(ctx, MerchantService_UpdateMerchantLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ProvisionMerchant(ctx context.Context, in *ProvisionMerchantRequest, opts ...grpc.CallOption) (*ProvisionMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_ProvisionMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
// All implementations must embed UnimplementedMerchantServiceServer
// for forward compatibility.
type MerchantServiceServer interface {
	GetMerchant(context.Context, *GetMerchantRequest) (*GetMerchantResponse, error)
	GetMerchantStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error)
	GetMerchantConfig(context.Context, *GetMerchantConfigRequest) (*GetMerchantConfigResponse, error)
	GetWebhookConfig(context.Context, *GetWebhookConfigRequest) (*GetWebhookConfigResponse, error)
	GetPayoutDestination(context.Context, *GetPayoutDestinationRequest) (*GetPayoutDestinationResponse, error)
	// Admin endpoints
	ListMerchants(context.Context, *ListMerchantsRequest) (*ListMerchantsResponse, error)
	SuspendMerchant(context.Context, *SuspendMerchantRequest) (*SuspendMerchantResponse, error)
	UpdateMerchantLimit(context.Context, *UpdateMerchantLimitRequest) (*UpdateMerchantLimitResponse, error)
	// Provisioning
	ProvisionMerchant(context.Context, *ProvisionMerchantRequest) (*ProvisionMerchantResponse, error)
	mustEmbedUnimplementedMerchantServiceServer()
}

// UnimplementedMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantServiceServer struct{}

func (UnimplementedMerchantServiceServer) GetMerchant(context.Context, *GetMerchantRequest) (*GetMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) GetMerchantStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchantStatus not implemented")
}
func (UnimplementedMerchantServiceServer) ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateApiKey not implemented")
}
func (UnimplementedMerchantServiceServer) GetMerchantConfig(context.Context, *GetMerchantConfigRequest) (*GetMerchantConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchantConfig not implemented")
}
func (UnimplementedMerchantServiceServer) GetWebhookConfig(context.Context, *GetWebhookConfigRequest) (*GetWebhookConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookConfig not implemented")
}
func (UnimplementedMerchantServiceServer) GetPayoutDestination(context.Context, *GetPayoutDestinationRequest) (*GetPayoutDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayoutDestination not implemented")
}
func (UnimplementedMerchantServiceServer) ListMerchants(context.Context, *ListMerchantsRequest) (*ListMerchantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMerchants not implemented")
}
func (UnimplementedMerchantServiceServer) SuspendMerchant(context.Context, *SuspendMerchantRequest) (*SuspendMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) UpdateMerchantLimit(context.Context, *UpdateMerchantLimitRequest) (*UpdateMerchantLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMerchantLimit not implemented")
}
func (UnimplementedMerchantServiceServer) ProvisionMerchant(context.Context, *ProvisionMerchantRequest) (*ProvisionMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) mustEmbedUnimplementedMerchantServiceServer() {}
func (UnimplementedMerchantServiceServer) testEmbeddedByValue()                         {}

// UnsafeMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantServiceServer will
// result in compilation errors.
type UnsafeMerchantServiceServer interface {
	mustEmbedUnimplementedMerchantServiceServer()
}

func RegisterMerchantServiceServer(s grpc.ServiceRegistrar, srv MerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantService_ServiceDesc, srv)
}

func _MerchantService_GetMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchant(ctx, req.(*GetMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchantStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ValidateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ValidateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ValidateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ValidateApiKey(ctx, req.(*ValidateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchantConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchantConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchantConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchantConfig(ctx, req.(*GetMerchantConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetWebhookConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetWebhookConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetWebhookConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetWebhookConfig(ctx, req.(*GetWebhookConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetPayoutDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayoutDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetPayoutDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetPayoutDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetPayoutDestination(ctx, req.(*GetPayoutDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ListMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ListMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ListMerchants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ListMerchants(ctx, req.(*ListMerchantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_SuspendMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).SuspendMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_SuspendMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).SuspendMerchant(ctx, req.(*SuspendMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_UpdateMerchantLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).UpdateMerchantLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_UpdateMerchantLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).UpdateMerchantLimit(ctx, req.(*UpdateMerchantLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ProvisionMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ProvisionMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ProvisionMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ProvisionMerchant(ctx, req.(*ProvisionMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantService_ServiceDesc is the grpc.ServiceDesc for MerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "merchant.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMerchant",
			Handler:    _MerchantService_GetMerchant_Handler,
		},
		{
			MethodName: "GetMerchantStatus",
			Handler:    _MerchantService_GetMerchantStatus_Handler,
		},
		{
			MethodName: "ValidateApiKey",
			Handler:    _MerchantService_ValidateApiKey_Handler,
		},
		{
			MethodName: "GetMerchantConfig",
			Handler:    _MerchantService_GetMerchantConfig_Handler,
		},
		{
			MethodName: "GetWebhookConfig",
			Handler:    _MerchantService_GetWebhookConfig_Handler,
		},
		{
			MethodName: "GetPayoutDestination",
			Handler:    _MerchantService_GetPayoutDestination_Handler,
		},
		{
			MethodName: "ListMerchants",
			Handler:    _MerchantService_ListMerchants_Handler,
		},
		{
			MethodName: "SuspendMerchant",
			Handler:    _MerchantService_SuspendMerchant_Handler,
		},
		{
			MethodName: "UpdateMerchantLimit",
			Handler:    _MerchantService_UpdateMerchantLimit_Handler,
		},
		{
			MethodName: "ProvisionMerchant",
			Handler:    _MerchantService_ProvisionMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}
