// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	BusinessName  string                 `protobuf:"bytes,3,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMerchantRequest) Reset() {
	*x = ProvisionMerchantRequest{}
	mi := &file_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMerchantRequest) ProtoMessage() {}

func (x *ProvisionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMerchantRequest.ProtoReflect.Descriptor instead.
func (*ProvisionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ProvisionMerchantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProvisionMerchantRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

type ProvisionMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMerchantResponse) Reset() {
	*x = ProvisionMerchantResponse{}
	mi := &file_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMerchantResponse) ProtoMessage() {}

func (x *ProvisionMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMerchantResponse.ProtoReflect.Descriptor instead.
func (*ProvisionMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionMerchantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProvisionMerchantResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListMerchantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsRequest) Reset() {
	*x = ListMerchantsRequest{}
	mi := &file_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsRequest) ProtoMessage() {}

func (x *ListMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *ListMerchantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMerchantsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMerchantsResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Merchants     []*ListMerchantsResponse_MerchantInfo `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Total         int32                                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse) Reset() {
	*x = ListMerchantsResponse{}
	mi := &file_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse) ProtoMessage() {}

func (x *ListMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *ListMerchantsResponse) GetMerchants() []*ListMerchantsResponse_MerchantInfo {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *ListMerchantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SuspendMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendMerchantRequest) Reset() {
	*x = SuspendMerchantRequest{}
	mi := &file_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendMerchantRequest) ProtoMessage() {}

func (x *SuspendMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendMerchantRequest.ProtoReflect.Descriptor instead.
func (*SuspendMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *SuspendMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SuspendMerchantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SuspendMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendMerchantResponse) Reset() {
	*x = SuspendMerchantResponse{}
	mi := &file_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendMerchantResponse) ProtoMessage() {}

func (x *SuspendMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendMerchantResponse.ProtoReflect.Descriptor instead.
func (*SuspendMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *SuspendMerchantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SuspendMerchantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateMerchantLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	MinAmount     int64                  `protobuf:"varint,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     int64                  `protobuf:"varint,4,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantLimitRequest) Reset() {
	*x = UpdateMerchantLimitRequest{}
	mi := &file_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantLimitRequest) ProtoMessage() {}

func (x *UpdateMerchantLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantLimitRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantLimitRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMerchantLimitRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMerchantLimitRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateMerchantLimitRequest) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *UpdateMerchantLimitRequest) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

type UpdateMerchantLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantLimitResponse) Reset() {
	*x = UpdateMerchantLimitResponse{}
	mi := &file_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantLimitResponse) ProtoMessage() {}

func (x *UpdateMerchantLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantLimitResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantLimitResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMerchantLimitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatusRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *GetMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LegalName     string                 `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *GetMerchantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMerchantResponse) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *GetMerchantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ValidateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyRequest) Reset() {
	*x = ValidateApiKeyRequest{}
	mi := &file_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyRequest) ProtoMessage() {}

func (x *ValidateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateApiKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"` // e.g., 'test' or 'live'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyResponse) Reset() {
	*x = ValidateApiKeyResponse{}
	mi := &file_merchant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyResponse) ProtoMessage() {}

func (x *ValidateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateApiKeyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateApiKeyResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ValidateApiKeyResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type GetMerchantConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantConfigRequest) Reset() {
	*x = GetMerchantConfigRequest{}
	mi := &file_merchant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantConfigRequest) ProtoMessage() {}

func (x *GetMerchantConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantConfigRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantConfigRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{14}
}

func (x *GetMerchantConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantConfigResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MerchantId            string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Version               int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	FeeRouting            string                 `protobuf:"bytes,3,opt,name=fee_routing,json=feeRouting,proto3" json:"fee_routing,omitempty"`
	EnabledPaymentMethods []string               `protobuf:"bytes,4,rep,name=enabled_payment_methods,json=enabledPaymentMethods,proto3" json:"enabled_payment_methods,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetMerchantConfigResponse) Reset() {
	*x = GetMerchantConfigResponse{}
	mi := &file_merchant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantConfigResponse) ProtoMessage() {}

func (x *GetMerchantConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantConfigResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantConfigResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{15}
}

func (x *GetMerchantConfigResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetMerchantConfigResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetMerchantConfigResponse) GetFeeRouting() string {
	if x != nil {
		return x.FeeRouting
	}
	return ""
}

func (x *GetMerchantConfigResponse) GetEnabledPaymentMethods() []string {
	if x != nil {
		return x.EnabledPaymentMethods
	}
	return nil
}

type GetWebhookConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"` // e.g., 'TEST' or 'LIVE'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookConfigRequest) Reset() {
	*x = GetWebhookConfigRequest{}
	mi := &file_merchant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookConfigRequest) ProtoMessage() {}

func (x *GetWebhookConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookConfigRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookConfigRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{16}
}

func (x *GetWebhookConfigRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetWebhookConfigRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type GetWebhookConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookUrl    string                 `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	HmacSecret    string                 `protobuf:"bytes,2,opt,name=hmac_secret,json=hmacSecret,proto3" json:"hmac_secret,omitempty"` // Protected in transit by mTLS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookConfigResponse) Reset() {
	*x = GetWebhookConfigResponse{}
	mi := &file_merchant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookConfigResponse) ProtoMessage() {}

func (x *GetWebhookConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookConfigResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookConfigResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{17}
}

func (x *GetWebhookConfigResponse) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *GetWebhookConfigResponse) GetHmacSecret() string {
	if x != nil {
		return x.HmacSecret
	}
	return ""
}

type GetPayoutDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutDestinationRequest) Reset() {
	*x = GetPayoutDestinationRequest{}
	mi := &file_merchant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutDestinationRequest) ProtoMessage() {}

func (x *GetPayoutDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutDestinationRequest.ProtoReflect.Descriptor instead.
func (*GetPayoutDestinationRequest) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{18}
}

func (x *GetPayoutDestinationRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetPayoutDestinationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPayoutDestinationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DestinationToken string                 `protobuf:"bytes,1,opt,name=destination_token,json=destinationToken,proto3" json:"destination_token,omitempty"` // Tokenized reference instead of raw bank details
	DestinationBank  string                 `protobuf:"bytes,2,opt,name=destination_bank,json=destinationBank,proto3" json:"destination_bank,omitempty"`
	ProviderId       string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPayoutDestinationResponse) Reset() {
	*x = GetPayoutDestinationResponse{}
	mi := &file_merchant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutDestinationResponse) ProtoMessage() {}

func (x *GetPayoutDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutDestinationResponse.ProtoReflect.Descriptor instead.
func (*GetPayoutDestinationResponse) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{19}
}

func (x *GetPayoutDestinationResponse) GetDestinationToken() string {
	if x != nil {
		return x.DestinationToken
	}
	return ""
}

func (x *GetPayoutDestinationResponse) GetDestinationBank() string {
	if x != nil {
		return x.DestinationBank
	}
	return ""
}

func (x *GetPayoutDestinationResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type ListMerchantsResponse_MerchantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LegalName     string                 `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse_MerchantInfo) Reset() {
	*x = ListMerchantsResponse_MerchantInfo{}
	mi := &file_merchant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse_MerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse_MerchantInfo) ProtoMessage() {}

func (x *ListMerchantsResponse_MerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse_MerchantInfo.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse_MerchantInfo) Descriptor() ([]byte, []int) {
	return file_merchant_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListMerchantsResponse_MerchantInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListMerchantsResponse_MerchantInfo) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *ListMerchantsResponse_MerchantInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListMerchantsResponse_MerchantInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_merchant_proto protoreflect.FileDescriptor

const file_merchant_proto_rawDesc = "" +
	"\n" +
	"\x0emerchant.proto\x12\bmerchant\"v\n" +
	"\x18ProvisionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rbusiness_name\x18\x03 \x01(\tR\fbusinessName\"K\n" +
	"\x19ProvisionMerchantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x14ListMerchantsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xef\x01\n" +
	"\x15ListMerchantsResponse\x12J\n" +
	"\tmerchants\x18\x01 \x03(\v2,.merchant.ListMerchantsResponse.MerchantInfoR\tmerchants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x1at\n" +
	"\fMerchantInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tR\tlegalName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"Q\n" +
	"\x16SuspendMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x17SuspendMerchantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x97\x01\n" +
	"\x1aUpdateMerchantLimitRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x03 \x01(\x03R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x04 \x01(\x03R\tmaxAmount\"7\n" +
	"\x1bUpdateMerchantLimitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x10GetStatusRequest\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x01 \x01(\tR\n" +
	"merchantId\"C\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"5\n" +
	"\x12GetMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\\\n" +
	"\x13GetMerchantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tR\tlegalName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"0\n" +
	"\x15ValidateApiKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"v\n" +
	"\x16ValidateApiKeyResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\";\n" +
	"\x18GetMerchantConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\xaf\x01\n" +
	"\x19GetMerchantConfigResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1f\n" +
	"\vfee_routing\x18\x03 \x01(\tR\n" +
	"feeRouting\x126\n" +
	"\x17enabled_payment_methods\x18\x04 \x03(\tR\x15enabledPaymentMethods\"\\\n" +
	"\x17GetWebhookConfigRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\"\\\n" +
	"\x18GetWebhookConfigResponse\x12\x1f\n" +
	"\vwebhook_url\x18\x01 \x01(\tR\n" +
	"webhookUrl\x12\x1f\n" +
	"\vhmac_secret\x18\x02 \x01(\tR\n" +
	"hmacSecret\"Z\n" +
	"\x1bGetPayoutDestinationRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x97\x01\n" +
	"\x1cGetPayoutDestinationResponse\x12+\n" +
	"\x11destination_token\x18\x01 \x01(\tR\x10destinationToken\x12)\n" +
	"\x10destination_bank\x18\x02 \x01(\tR\x0fdestinationBank\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId2\x8c\a\n" +
	"\x0fMerchantService\x12J\n" +
	"\vGetMerchant\x12\x1c.merchant.GetMerchantRequest\x1a\x1d.merchant.GetMerchantResponse\x12L\n" +
	"\x11GetMerchantStatus\x12\x1a.merchant.GetStatusRequest\x1a\x1b.merchant.GetStatusResponse\x12S\n" +
	"\x0eValidateApiKey\x12\x1f.merchant.ValidateApiKeyRequest\x1a .merchant.ValidateApiKeyResponse\x12\\\n" +
	"\x11GetMerchantConfig\x12\".merchant.GetMerchantConfigRequest\x1a#.merchant.GetMerchantConfigResponse\x12Y\n" +
	"\x10GetWebhookConfig\x12!.merchant.GetWebhookConfigRequest\x1a\".merchant.GetWebhookConfigResponse\x12e\n" +
	"\x14GetPayoutDestination\x12%.merchant.GetPayoutDestinationRequest\x1a&.merchant.GetPayoutDestinationResponse\x12P\n" +
	"\rListMerchants\x12\x1e.merchant.ListMerchantsRequest\x1a\x1f.merchant.ListMerchantsResponse\x12V\n" +
	"\x0fSuspendMerchant\x12 .merchant.SuspendMerchantRequest\x1a!.merchant.SuspendMerchantResponse\x12b\n" +
	"\x13UpdateMerchantLimit\x12$.merchant.UpdateMerchantLimitRequest\x1a%.merchant.UpdateMerchantLimitResponse\x12\\\n" +
	"\x11ProvisionMerchant\x12\".merchant.ProvisionMerchantRequest\x1a#.merchant.ProvisionMerchantResponseB'Z%payment-gateway/payment-service/protob\x06proto3"

var (
	file_merchant_proto_rawDescOnce sync.Once
	file_merchant_proto_rawDescData []byte
)

func file_merchant_proto_rawDescGZIP() []byte {
	file_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)))
	})
	return file_merchant_proto_rawDescData
}

var file_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_merchant_proto_goTypes = []any{
	(*ProvisionMerchantRequest)(nil),           // 0: merchant.ProvisionMerchantRequest
	(*ProvisionMerchantResponse)(nil),          // 1: merchant.ProvisionMerchantResponse
	(*ListMerchantsRequest)(nil),               // 2: merchant.ListMerchantsRequest
	(*ListMerchantsResponse)(nil),              // 3: merchant.ListMerchantsResponse
	(*SuspendMerchantRequest)(nil),             // 4: merchant.SuspendMerchantRequest
	(*SuspendMerchantResponse)(nil),            // 5: merchant.SuspendMerchantResponse
	(*UpdateMerchantLimitRequest)(nil),         // 6: merchant.UpdateMerchantLimitRequest
	(*UpdateMerchantLimitResponse)(nil),        // 7: merchant.UpdateMerchantLimitResponse
	(*GetStatusRequest)(nil),                   // 8: merchant.GetStatusRequest
	(*GetStatusResponse)(nil),                  // 9: merchant.GetStatusResponse
	(*GetMerchantRequest)(nil),                 // 10: merchant.GetMerchantRequest
	(*GetMerchantResponse)(nil),                // 11: merchant.GetMerchantResponse
	(*ValidateApiKeyRequest)(nil),              // 12: merchant.ValidateApiKeyRequest
	(*ValidateApiKeyResponse)(nil),             // 13: merchant.ValidateApiKeyResponse
	(*GetMerchantConfigRequest)(nil),           // 14: merchant.GetMerchantConfigRequest
	(*GetMerchantConfigResponse)(nil),          // 15: merchant.GetMerchantConfigResponse
	(*GetWebhookConfigRequest)(nil),            // 16: merchant.GetWebhookConfigRequest
	(*GetWebhookConfigResponse)(nil),           // 17: merchant.GetWebhookConfigResponse
	(*GetPayoutDestinationRequest)(nil),        // 18: merchant.GetPayoutDestinationRequest
	(*GetPayoutDestinationResponse)(nil),       // 19: merchant.GetPayoutDestinationResponse
	(*ListMerchantsResponse_MerchantInfo)(nil), // 20: merchant.ListMerchantsResponse.MerchantInfo
}
var file_merchant_proto_depIdxs = []int32{
	20, // 0: merchant.ListMerchantsResponse.merchants:type_name -> merchant.ListMerchantsResponse.MerchantInfo
	10, // 1: merchant.MerchantService.GetMerchant:input_type -> merchant.GetMerchantRequest
	8,  // 2: merchant.MerchantService.GetMerchantStatus:input_type -> merchant.GetStatusRequest
	12, // 3: merchant.MerchantService.ValidateApiKey:input_type -> merchant.ValidateApiKeyRequest
	14, // 4: merchant.MerchantService.GetMerchantConfig:input_type -> merchant.GetMerchantConfigRequest
	16, // 5: merchant.MerchantService.GetWebhookConfig:input_type -> merchant.GetWebhookConfigRequest
	18, // 6: merchant.MerchantService.GetPayoutDestination:input_type -> merchant.GetPayoutDestinationRequest
	2,  // 7: merchant.MerchantService.ListMerchants:input_type -> merchant.ListMerchantsRequest
	4,  // 8: merchant.MerchantService.SuspendMerchant:input_type -> merchant.SuspendMerchantRequest
	6,  // 9: merchant.MerchantService.UpdateMerchantLimit:input_type -> merchant.UpdateMerchantLimitRequest
	0,  // 10: merchant.MerchantService.ProvisionMerchant:input_type -> merchant.ProvisionMerchantRequest
	11, // 11: merchant.MerchantService.GetMerchant:output_type -> merchant.GetMerchantResponse
	9,  // 12: merchant.MerchantService.GetMerchantStatus:output_type -> merchant.GetStatusResponse
	13, // 13: merchant.MerchantService.ValidateApiKey:output_type -> merchant.ValidateApiKeyResponse
	15, // 14: merchant.MerchantService.GetMerchantConfig:output_type -> merchant.GetMerchantConfigResponse
	17, // 15: merchant.MerchantService.GetWebhookConfig:output_type -> merchant.GetWebhookConfigResponse
	19, // 16: merchant.MerchantService.GetPayoutDestination:output_type -> merchant.GetPayoutDestinationResponse
	3,  // 17: merchant.MerchantService.ListMerchants:output_type -> merchant.ListMerchantsResponse
	5,  // 18: merchant.MerchantService.SuspendMerchant:output_type -> merchant.SuspendMerchantResponse
	7,  // 19: merchant.MerchantService.UpdateMerchantLimit:output_type -> merchant.UpdateMerchantLimitResponse
	1,  // 20: merchant.MerchantService.ProvisionMerchant:output_type -> merchant.ProvisionMerchantResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_proto_init() }
func file_merchant_proto_init() {
	if File_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_proto_rawDesc), len(file_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_proto_depIdxs,
		MessageInfos:      file_merchant_proto_msgTypes,
	}.Build()
	File_merchant_proto = out.File
	file_merchant_proto_goTypes = nil
	file_merchant_proto_depIdxs = nil
}
