// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: payment_read.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentReadService_GetPayments_FullMethodName             = "/payment_read.PaymentReadService/GetPayments"
	PaymentReadService_GetPayment_FullMethodName              = "/payment_read.PaymentReadService/GetPayment"
	PaymentReadService_GetPaymentStatusHistory_FullMethodName = "/payment_read.PaymentReadService/GetPaymentStatusHistory"
	PaymentReadService_GetRefunds_FullMethodName              = "/payment_read.PaymentReadService/GetRefunds"
)

// PaymentReadServiceClient is the client API for PaymentReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BFF Read APIs for the Payment Service.
// All RPCs require RequestContext to be present in gRPC metadata.
// Handlers MUST call RequireMerchant(ctx, req.merchant_id) before querying the DB.
type PaymentReadServiceClient interface {
	GetPayments(ctx context.Context, in *GetPaymentsRequest, opts ...grpc.CallOption) (*GetPaymentsResponse, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
	GetPaymentStatusHistory(ctx context.Context, in *GetPaymentStatusHistoryRequest, opts ...grpc.CallOption) (*GetPaymentStatusHistoryResponse, error)
	GetRefunds(ctx context.Context, in *GetRefundsRequest, opts ...grpc.CallOption) (*GetRefundsResponse, error)
}

type paymentReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentReadServiceClient(cc grpc.ClientConnInterface) PaymentReadServiceClient {
	return &paymentReadServiceClient{cc}
}

func (c *paymentReadServiceClient) GetPayments(ctx context.Context, in *GetPaymentsRequest, opts ...grpc.CallOption) (*GetPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentsResponse)
	err := c.cc.Invoke(ctx, PaymentReadService_GetPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentReadServiceClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentReadService_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentReadServiceClient) GetPaymentStatusHistory(ctx context.Context, in *GetPaymentStatusHistoryRequest, opts ...grpc.CallOption) (*GetPaymentStatusHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentStatusHistoryResponse)
	err := c.cc.Invoke(ctx, PaymentReadService_GetPaymentStatusHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentReadServiceClient) GetRefunds(ctx context.Context, in *GetRefundsRequest, opts ...grpc.CallOption) (*GetRefundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRefundsResponse)
	err := c.cc.Invoke(ctx, PaymentReadService_GetRefunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentReadServiceServer is the server API for PaymentReadService service.
// All implementations must embed UnimplementedPaymentReadServiceServer
// for forward compatibility.
//
// BFF Read APIs for the Payment Service.
// All RPCs require RequestContext to be present in gRPC metadata.
// Handlers MUST call RequireMerchant(ctx, req.merchant_id) before querying the DB.
type PaymentReadServiceServer interface {
	GetPayments(context.Context, *GetPaymentsRequest) (*GetPaymentsResponse, error)
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	GetPaymentStatusHistory(context.Context, *GetPaymentStatusHistoryRequest) (*GetPaymentStatusHistoryResponse, error)
	GetRefunds(context.Context, *GetRefundsRequest) (*GetRefundsResponse, error)
	mustEmbedUnimplementedPaymentReadServiceServer()
}

// UnimplementedPaymentReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentReadServiceServer struct{}

func (UnimplementedPaymentReadServiceServer) GetPayments(context.Context, *GetPaymentsRequest) (*GetPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayments not implemented")
}
func (UnimplementedPaymentReadServiceServer) GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentReadServiceServer) GetPaymentStatusHistory(context.Context, *GetPaymentStatusHistoryRequest) (*GetPaymentStatusHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentStatusHistory not implemented")
}
func (UnimplementedPaymentReadServiceServer) GetRefunds(context.Context, *GetRefundsRequest) (*GetRefundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRefunds not implemented")
}
func (UnimplementedPaymentReadServiceServer) mustEmbedUnimplementedPaymentReadServiceServer() {}
func (UnimplementedPaymentReadServiceServer) testEmbeddedByValue()                            {}

// UnsafePaymentReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentReadServiceServer will
// result in compilation errors.
type UnsafePaymentReadServiceServer interface {
	mustEmbedUnimplementedPaymentReadServiceServer()
}

func RegisterPaymentReadServiceServer(s grpc.ServiceRegistrar, srv PaymentReadServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentReadService_ServiceDesc, srv)
}

func _PaymentReadService_GetPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentReadServiceServer).GetPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentReadService_GetPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentReadServiceServer).GetPayments(ctx, req.(*GetPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentReadService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentReadServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentReadService_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentReadServiceServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentReadService_GetPaymentStatusHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentStatusHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentReadServiceServer).GetPaymentStatusHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentReadService_GetPaymentStatusHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentReadServiceServer).GetPaymentStatusHistory(ctx, req.(*GetPaymentStatusHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentReadService_GetRefunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRefundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentReadServiceServer).GetRefunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentReadService_GetRefunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentReadServiceServer).GetRefunds(ctx, req.(*GetRefundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentReadService_ServiceDesc is the grpc.ServiceDesc for PaymentReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_read.PaymentReadService",
	HandlerType: (*PaymentReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayments",
			Handler:    _PaymentReadService_GetPayments_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _PaymentReadService_GetPayment_Handler,
		},
		{
			MethodName: "GetPaymentStatusHistory",
			Handler:    _PaymentReadService_GetPaymentStatusHistory_Handler,
		},
		{
			MethodName: "GetRefunds",
			Handler:    _PaymentReadService_GetRefunds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_read.proto",
}
