// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: payment_write.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutePaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantId      string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"` // Can be empty if using default or redirect
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutePaymentRequest) Reset() {
	*x = ExecutePaymentRequest{}
	mi := &file_payment_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePaymentRequest) ProtoMessage() {}

func (x *ExecutePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePaymentRequest.ProtoReflect.Descriptor instead.
func (*ExecutePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_write_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutePaymentRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ExecutePaymentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *ExecutePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExecutePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ExecutePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ExecutePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePaymentResponse) Reset() {
	*x = ExecutePaymentResponse{}
	mi := &file_payment_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePaymentResponse) ProtoMessage() {}

func (x *ExecutePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePaymentResponse.ProtoReflect.Descriptor instead.
func (*ExecutePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_write_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ExecutePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_payment_write_proto protoreflect.FileDescriptor

const file_payment_write_proto_rawDesc = "" +
	"\n" +
	"\x13payment_write.proto\x12\rpayment_write\"\xc1\x01\n" +
	"\x15ExecutePaymentRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"O\n" +
	"\x16ExecutePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2t\n" +
	"\x13PaymentWriteService\x12]\n" +
	"\x0eExecutePayment\x12$.payment_write.ExecutePaymentRequest\x1a%.payment_write.ExecutePaymentResponseB'Z%payment-gateway/payment-service/protob\x06proto3"

var (
	file_payment_write_proto_rawDescOnce sync.Once
	file_payment_write_proto_rawDescData []byte
)

func file_payment_write_proto_rawDescGZIP() []byte {
	file_payment_write_proto_rawDescOnce.Do(func() {
		file_payment_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_write_proto_rawDesc), len(file_payment_write_proto_rawDesc)))
	})
	return file_payment_write_proto_rawDescData
}

var file_payment_write_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_payment_write_proto_goTypes = []any{
	(*ExecutePaymentRequest)(nil),  // 0: payment_write.ExecutePaymentRequest
	(*ExecutePaymentResponse)(nil), // 1: payment_write.ExecutePaymentResponse
}
var file_payment_write_proto_depIdxs = []int32{
	0, // 0: payment_write.PaymentWriteService.ExecutePayment:input_type -> payment_write.ExecutePaymentRequest
	1, // 1: payment_write.PaymentWriteService.ExecutePayment:output_type -> payment_write.ExecutePaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_write_proto_init() }
func file_payment_write_proto_init() {
	if File_payment_write_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_write_proto_rawDesc), len(file_payment_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_write_proto_goTypes,
		DependencyIndexes: file_payment_write_proto_depIdxs,
		MessageInfos:      file_payment_write_proto_msgTypes,
	}.Build()
	File_payment_write_proto = out.File
	file_payment_write_proto_goTypes = nil
	file_payment_write_proto_depIdxs = nil
}
