// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: routing.proto

package routing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetermineRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bin           string                 `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`                                 // The first 6-8 digits of the card (Bank Identification Number)
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                       // Payment currency (e.g., USD, EUR, ETB)
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                          // Payment amount in minor units
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // To check merchant specific routing rules/preferences
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetermineRouteRequest) Reset() {
	*x = DetermineRouteRequest{}
	mi := &file_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetermineRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetermineRouteRequest) ProtoMessage() {}

func (x *DetermineRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetermineRouteRequest.ProtoReflect.Descriptor instead.
func (*DetermineRouteRequest) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{0}
}

func (x *DetermineRouteRequest) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *DetermineRouteRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DetermineRouteRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DetermineRouteRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type DetermineRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`        // The selected provider ID (e.g. telebirr, stripe, adyen)
	RouteReason   string                 `protobuf:"bytes,2,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`     // Explanation for auditing (e.g. "lowest_cost", "fallback_routing")
	EstimatedFee  int32                  `protobuf:"varint,3,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"` // Estimated interchange/processing fee in minor units
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetermineRouteResponse) Reset() {
	*x = DetermineRouteResponse{}
	mi := &file_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetermineRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetermineRouteResponse) ProtoMessage() {}

func (x *DetermineRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetermineRouteResponse.ProtoReflect.Descriptor instead.
func (*DetermineRouteResponse) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{1}
}

func (x *DetermineRouteResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *DetermineRouteResponse) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

func (x *DetermineRouteResponse) GetEstimatedFee() int32 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

var File_routing_proto protoreflect.FileDescriptor

const file_routing_proto_rawDesc = "" +
	"\n" +
	"\rrouting.proto\x12\arouting\"~\n" +
	"\x15DetermineRouteRequest\x12\x10\n" +
	"\x03bin\x18\x01 \x01(\tR\x03bin\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\"\x81\x01\n" +
	"\x16DetermineRouteResponse\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\froute_reason\x18\x02 \x01(\tR\vrouteReason\x12#\n" +
	"\restimated_fee\x18\x03 \x01(\x05R\festimatedFee2c\n" +
	"\x0eRoutingService\x12Q\n" +
	"\x0eDetermineRoute\x12\x1e.routing.DetermineRouteRequest\x1a\x1f.routing.DetermineRouteResponseB8Z6payment-gateway/services/routing-service/proto;routingb\x06proto3"

var (
	file_routing_proto_rawDescOnce sync.Once
	file_routing_proto_rawDescData []byte
)

func file_routing_proto_rawDescGZIP() []byte {
	file_routing_proto_rawDescOnce.Do(func() {
		file_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)))
	})
	return file_routing_proto_rawDescData
}

var file_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routing_proto_goTypes = []any{
	(*DetermineRouteRequest)(nil),  // 0: routing.DetermineRouteRequest
	(*DetermineRouteResponse)(nil), // 1: routing.DetermineRouteResponse
}
var file_routing_proto_depIdxs = []int32{
	0, // 0: routing.RoutingService.DetermineRoute:input_type -> routing.DetermineRouteRequest
	1, // 1: routing.RoutingService.DetermineRoute:output_type -> routing.DetermineRouteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routing_proto_init() }
func file_routing_proto_init() {
	if File_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routing_proto_goTypes,
		DependencyIndexes: file_routing_proto_depIdxs,
		MessageInfos:      file_routing_proto_msgTypes,
	}.Build()
	File_routing_proto = out.File
	file_routing_proto_goTypes = nil
	file_routing_proto_depIdxs = nil
}
