// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ledger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordJournalEntryRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReferenceType         string                 `protobuf:"bytes,1,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId           string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Currency              string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Lines                 []*JournalLineRequest  `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	ProviderId            string                 `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,6,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	Environment           string                 `protobuf:"bytes,7,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RecordJournalEntryRequest) Reset() {
	*x = RecordJournalEntryRequest{}
	mi := &file_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordJournalEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordJournalEntryRequest) ProtoMessage() {}

func (x *RecordJournalEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordJournalEntryRequest.ProtoReflect.Descriptor instead.
func (*RecordJournalEntryRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *RecordJournalEntryRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *RecordJournalEntryRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *RecordJournalEntryRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecordJournalEntryRequest) GetLines() []*JournalLineRequest {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *RecordJournalEntryRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *RecordJournalEntryRequest) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *RecordJournalEntryRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type JournalLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"` // "DEBIT" or "CREDIT"
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalLineRequest) Reset() {
	*x = JournalLineRequest{}
	mi := &file_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalLineRequest) ProtoMessage() {}

func (x *JournalLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalLineRequest.ProtoReflect.Descriptor instead.
func (*JournalLineRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *JournalLineRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *JournalLineRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *JournalLineRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RecordJournalEntryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	JournalEntryId string                 `protobuf:"bytes,3,opt,name=journal_entry_id,json=journalEntryId,proto3" json:"journal_entry_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordJournalEntryResponse) Reset() {
	*x = RecordJournalEntryResponse{}
	mi := &file_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordJournalEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordJournalEntryResponse) ProtoMessage() {}

func (x *RecordJournalEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordJournalEntryResponse.ProtoReflect.Descriptor instead.
func (*RecordJournalEntryResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *RecordJournalEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordJournalEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RecordJournalEntryResponse) GetJournalEntryId() string {
	if x != nil {
		return x.JournalEntryId
	}
	return ""
}

type GetLedgerEntriesRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProviderId             string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderTransactionIds []string               `protobuf:"bytes,2,rep,name=provider_transaction_ids,json=providerTransactionIds,proto3" json:"provider_transaction_ids,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetLedgerEntriesRequest) Reset() {
	*x = GetLedgerEntriesRequest{}
	mi := &file_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntriesRequest) ProtoMessage() {}

func (x *GetLedgerEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerEntriesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *GetLedgerEntriesRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetLedgerEntriesRequest) GetProviderTransactionIds() []string {
	if x != nil {
		return x.ProviderTransactionIds
	}
	return nil
}

type GetLedgerEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerEntriesResponse) Reset() {
	*x = GetLedgerEntriesResponse{}
	mi := &file_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntriesResponse) ProtoMessage() {}

func (x *GetLedgerEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerEntriesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetLedgerEntriesResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReserveFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // Settlement ID
	Environment   string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveFundsRequest) Reset() {
	*x = ReserveFundsRequest{}
	mi := &file_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveFundsRequest) ProtoMessage() {}

func (x *ReserveFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveFundsRequest.ProtoReflect.Descriptor instead.
func (*ReserveFundsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveFundsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReserveFundsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReserveFundsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReserveFundsRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *ReserveFundsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ReserveFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveFundsResponse) Reset() {
	*x = ReserveFundsResponse{}
	mi := &file_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveFundsResponse) ProtoMessage() {}

func (x *ReserveFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveFundsResponse.ProtoReflect.Descriptor instead.
func (*ReserveFundsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveFundsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReleaseReservedFundsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MerchantId          string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency            string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount              int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	OriginalReferenceId string                 `protobuf:"bytes,4,opt,name=original_reference_id,json=originalReferenceId,proto3" json:"original_reference_id,omitempty"` // Settlement ID
	Environment         string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReleaseReservedFundsRequest) Reset() {
	*x = ReleaseReservedFundsRequest{}
	mi := &file_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservedFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservedFundsRequest) ProtoMessage() {}

func (x *ReleaseReservedFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservedFundsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservedFundsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseReservedFundsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReleaseReservedFundsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReleaseReservedFundsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReleaseReservedFundsRequest) GetOriginalReferenceId() string {
	if x != nil {
		return x.OriginalReferenceId
	}
	return ""
}

func (x *ReleaseReservedFundsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ReleaseReservedFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservedFundsResponse) Reset() {
	*x = ReleaseReservedFundsResponse{}
	mi := &file_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservedFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservedFundsResponse) ProtoMessage() {}

func (x *ReleaseReservedFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservedFundsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservedFundsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseReservedFundsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CompleteSettlementRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MerchantId          string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency            string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount              int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	OriginalReferenceId string                 `protobuf:"bytes,4,opt,name=original_reference_id,json=originalReferenceId,proto3" json:"original_reference_id,omitempty"` // Settlement ID
	Environment         string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteSettlementRequest) Reset() {
	*x = CompleteSettlementRequest{}
	mi := &file_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSettlementRequest) ProtoMessage() {}

func (x *CompleteSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSettlementRequest.ProtoReflect.Descriptor instead.
func (*CompleteSettlementRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteSettlementRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CompleteSettlementRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CompleteSettlementRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CompleteSettlementRequest) GetOriginalReferenceId() string {
	if x != nil {
		return x.OriginalReferenceId
	}
	return ""
}

func (x *CompleteSettlementRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type CompleteSettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSettlementResponse) Reset() {
	*x = CompleteSettlementResponse{}
	mi := &file_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSettlementResponse) ProtoMessage() {}

func (x *CompleteSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSettlementResponse.ProtoReflect.Descriptor instead.
func (*CompleteSettlementResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteSettlementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LedgerEntry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	JournalEntryId        string                 `protobuf:"bytes,1,opt,name=journal_entry_id,json=journalEntryId,proto3" json:"journal_entry_id,omitempty"`
	ReferenceType         string                 `protobuf:"bytes,2,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId           string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ProviderId            string                 `protobuf:"bytes,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,5,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	Amount                int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	EffectiveAt           string                 `protobuf:"bytes,8,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *LedgerEntry) GetJournalEntryId() string {
	if x != nil {
		return x.JournalEntryId
	}
	return ""
}

func (x *LedgerEntry) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *LedgerEntry) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *LedgerEntry) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *LedgerEntry) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *LedgerEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LedgerEntry) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

type GetLedgerBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Must match RequestContext.merchant_id
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                       // Optional: filter by currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerBalancesRequest) Reset() {
	*x = GetLedgerBalancesRequest{}
	mi := &file_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerBalancesRequest) ProtoMessage() {}

func (x *GetLedgerBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerBalancesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *GetLedgerBalancesRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetLedgerBalancesRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type AccountBalance struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType       string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AccountGroup      string                 `protobuf:"bytes,3,opt,name=account_group,json=accountGroup,proto3" json:"account_group,omitempty"`
	Currency          string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BalanceMinorUnits int64                  `protobuf:"varint,5,opt,name=balance_minor_units,json=balanceMinorUnits,proto3" json:"balance_minor_units,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *AccountBalance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountBalance) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountBalance) GetAccountGroup() string {
	if x != nil {
		return x.AccountGroup
	}
	return ""
}

func (x *AccountBalance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountBalance) GetBalanceMinorUnits() int64 {
	if x != nil {
		return x.BalanceMinorUnits
	}
	return 0
}

type GetLedgerBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*AccountBalance      `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerBalancesResponse) Reset() {
	*x = GetLedgerBalancesResponse{}
	mi := &file_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerBalancesResponse) ProtoMessage() {}

func (x *GetLedgerBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerBalancesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *GetLedgerBalancesResponse) GetBalances() []*AccountBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type GetLedgerEntriesPaginatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`    // Must match RequestContext.merchant_id
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                          // Optional filter
	AfterCursor   string                 `protobuf:"bytes,3,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"` // Cursor-based pagination; empty = first page
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                               // Max results per page; server enforces ceiling
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerEntriesPaginatedRequest) Reset() {
	*x = GetLedgerEntriesPaginatedRequest{}
	mi := &file_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntriesPaginatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntriesPaginatedRequest) ProtoMessage() {}

func (x *GetLedgerEntriesPaginatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntriesPaginatedRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerEntriesPaginatedRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *GetLedgerEntriesPaginatedRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetLedgerEntriesPaginatedRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetLedgerEntriesPaginatedRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

func (x *GetLedgerEntriesPaginatedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLedgerEntriesPaginatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Empty if no more pages
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerEntriesPaginatedResponse) Reset() {
	*x = GetLedgerEntriesPaginatedResponse{}
	mi := &file_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntriesPaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntriesPaginatedResponse) ProtoMessage() {}

func (x *GetLedgerEntriesPaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntriesPaginatedResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerEntriesPaginatedResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *GetLedgerEntriesPaginatedResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLedgerEntriesPaginatedResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetLedgerEntriesPaginatedResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_ledger_proto protoreflect.FileDescriptor

const file_ledger_proto_rawDesc = "" +
	"\n" +
	"\fledger.proto\x12\x06ledger\"\xae\x02\n" +
	"\x19RecordJournalEntryRequest\x12%\n" +
	"\x0ereference_type\x18\x01 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x120\n" +
	"\x05lines\x18\x04 \x03(\v2\x1a.ledger.JournalLineRequestR\x05lines\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\x126\n" +
	"\x17provider_transaction_id\x18\x06 \x01(\tR\x15providerTransactionId\x12 \n" +
	"\venvironment\x18\a \x01(\tR\venvironment\"i\n" +
	"\x12JournalLineRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"v\n" +
	"\x1aRecordJournalEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\x10journal_entry_id\x18\x03 \x01(\tR\x0ejournalEntryId\"t\n" +
	"\x17GetLedgerEntriesRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x128\n" +
	"\x18provider_transaction_ids\x18\x02 \x03(\tR\x16providerTransactionIds\"I\n" +
	"\x18GetLedgerEntriesResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.ledger.LedgerEntryR\aentries\"\xaf\x01\n" +
	"\x13ReserveFundsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\".\n" +
	"\x14ReserveFundsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc8\x01\n" +
	"\x1bReleaseReservedFundsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x122\n" +
	"\x15original_reference_id\x18\x04 \x01(\tR\x13originalReferenceId\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\"6\n" +
	"\x1cReleaseReservedFundsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc6\x01\n" +
	"\x19CompleteSettlementRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x122\n" +
	"\x15original_reference_id\x18\x04 \x01(\tR\x13originalReferenceId\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\"4\n" +
	"\x1aCompleteSettlementResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb1\x02\n" +
	"\vLedgerEntry\x12(\n" +
	"\x10journal_entry_id\x18\x01 \x01(\tR\x0ejournalEntryId\x12%\n" +
	"\x0ereference_type\x18\x02 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\tR\n" +
	"providerId\x126\n" +
	"\x17provider_transaction_id\x18\x05 \x01(\tR\x15providerTransactionId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12!\n" +
	"\feffective_at\x18\b \x01(\tR\veffectiveAt\"W\n" +
	"\x18GetLedgerBalancesRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xc3\x01\n" +
	"\x0eAccountBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12#\n" +
	"\raccount_group\x18\x03 \x01(\tR\faccountGroup\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12.\n" +
	"\x13balance_minor_units\x18\x05 \x01(\x03R\x11balanceMinorUnits\"O\n" +
	"\x19GetLedgerBalancesResponse\x122\n" +
	"\bbalances\x18\x01 \x03(\v2\x16.ledger.AccountBalanceR\bbalances\"\x98\x01\n" +
	" GetLedgerEntriesPaginatedRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12!\n" +
	"\fafter_cursor\x18\x03 \x01(\tR\vafterCursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x8e\x01\n" +
	"!GetLedgerEntriesPaginatedResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.ledger.LedgerEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xa6\x05\n" +
	"\rLedgerService\x12[\n" +
	"\x12RecordJournalEntry\x12!.ledger.RecordJournalEntryRequest\x1a\".ledger.RecordJournalEntryResponse\x12a\n" +
	"\x1cGetLedgerEntriesByReferences\x12\x1f.ledger.GetLedgerEntriesRequest\x1a .ledger.GetLedgerEntriesResponse\x12I\n" +
	"\fReserveFunds\x12\x1b.ledger.ReserveFundsRequest\x1a\x1c.ledger.ReserveFundsResponse\x12a\n" +
	"\x14ReleaseReservedFunds\x12#.ledger.ReleaseReservedFundsRequest\x1a$.ledger.ReleaseReservedFundsResponse\x12[\n" +
	"\x12CompleteSettlement\x12!.ledger.CompleteSettlementRequest\x1a\".ledger.CompleteSettlementResponse\x12X\n" +
	"\x11GetLedgerBalances\x12 .ledger.GetLedgerBalancesRequest\x1a!.ledger.GetLedgerBalancesResponse\x12p\n" +
	"\x19GetLedgerEntriesPaginated\x12(.ledger.GetLedgerEntriesPaginatedRequest\x1a).ledger.GetLedgerEntriesPaginatedResponseB&Z$payment-gateway/ledger-service/protob\x06proto3"

var (
	file_ledger_proto_rawDescOnce sync.Once
	file_ledger_proto_rawDescData []byte
)

func file_ledger_proto_rawDescGZIP() []byte {
	file_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_proto_rawDesc), len(file_ledger_proto_rawDesc)))
	})
	return file_ledger_proto_rawDescData
}

var file_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ledger_proto_goTypes = []any{
	(*RecordJournalEntryRequest)(nil),         // 0: ledger.RecordJournalEntryRequest
	(*JournalLineRequest)(nil),                // 1: ledger.JournalLineRequest
	(*RecordJournalEntryResponse)(nil),        // 2: ledger.RecordJournalEntryResponse
	(*GetLedgerEntriesRequest)(nil),           // 3: ledger.GetLedgerEntriesRequest
	(*GetLedgerEntriesResponse)(nil),          // 4: ledger.GetLedgerEntriesResponse
	(*ReserveFundsRequest)(nil),               // 5: ledger.ReserveFundsRequest
	(*ReserveFundsResponse)(nil),              // 6: ledger.ReserveFundsResponse
	(*ReleaseReservedFundsRequest)(nil),       // 7: ledger.ReleaseReservedFundsRequest
	(*ReleaseReservedFundsResponse)(nil),      // 8: ledger.ReleaseReservedFundsResponse
	(*CompleteSettlementRequest)(nil),         // 9: ledger.CompleteSettlementRequest
	(*CompleteSettlementResponse)(nil),        // 10: ledger.CompleteSettlementResponse
	(*LedgerEntry)(nil),                       // 11: ledger.LedgerEntry
	(*GetLedgerBalancesRequest)(nil),          // 12: ledger.GetLedgerBalancesRequest
	(*AccountBalance)(nil),                    // 13: ledger.AccountBalance
	(*GetLedgerBalancesResponse)(nil),         // 14: ledger.GetLedgerBalancesResponse
	(*GetLedgerEntriesPaginatedRequest)(nil),  // 15: ledger.GetLedgerEntriesPaginatedRequest
	(*GetLedgerEntriesPaginatedResponse)(nil), // 16: ledger.GetLedgerEntriesPaginatedResponse
}
var file_ledger_proto_depIdxs = []int32{
	1,  // 0: ledger.RecordJournalEntryRequest.lines:type_name -> ledger.JournalLineRequest
	11, // 1: ledger.GetLedgerEntriesResponse.entries:type_name -> ledger.LedgerEntry
	13, // 2: ledger.GetLedgerBalancesResponse.balances:type_name -> ledger.AccountBalance
	11, // 3: ledger.GetLedgerEntriesPaginatedResponse.entries:type_name -> ledger.LedgerEntry
	0,  // 4: ledger.LedgerService.RecordJournalEntry:input_type -> ledger.RecordJournalEntryRequest
	3,  // 5: ledger.LedgerService.GetLedgerEntriesByReferences:input_type -> ledger.GetLedgerEntriesRequest
	5,  // 6: ledger.LedgerService.ReserveFunds:input_type -> ledger.ReserveFundsRequest
	7,  // 7: ledger.LedgerService.ReleaseReservedFunds:input_type -> ledger.ReleaseReservedFundsRequest
	9,  // 8: ledger.LedgerService.CompleteSettlement:input_type -> ledger.CompleteSettlementRequest
	12, // 9: ledger.LedgerService.GetLedgerBalances:input_type -> ledger.GetLedgerBalancesRequest
	15, // 10: ledger.LedgerService.GetLedgerEntriesPaginated:input_type -> ledger.GetLedgerEntriesPaginatedRequest
	2,  // 11: ledger.LedgerService.RecordJournalEntry:output_type -> ledger.RecordJournalEntryResponse
	4,  // 12: ledger.LedgerService.GetLedgerEntriesByReferences:output_type -> ledger.GetLedgerEntriesResponse
	6,  // 13: ledger.LedgerService.ReserveFunds:output_type -> ledger.ReserveFundsResponse
	8,  // 14: ledger.LedgerService.ReleaseReservedFunds:output_type -> ledger.ReleaseReservedFundsResponse
	10, // 15: ledger.LedgerService.CompleteSettlement:output_type -> ledger.CompleteSettlementResponse
	14, // 16: ledger.LedgerService.GetLedgerBalances:output_type -> ledger.GetLedgerBalancesResponse
	16, // 17: ledger.LedgerService.GetLedgerEntriesPaginated:output_type -> ledger.GetLedgerEntriesPaginatedResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ledger_proto_init() }
func file_ledger_proto_init() {
	if File_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_proto_rawDesc), len(file_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_proto_msgTypes,
	}.Build()
	File_ledger_proto = out.File
	file_ledger_proto_goTypes = nil
	file_ledger_proto_depIdxs = nil
}
