// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ml.proto

package ml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateFraudRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IpAddress         string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	DeviceFingerprint string                 `protobuf:"bytes,2,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	Amount            int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CustomerId        string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Bin               string                 `protobuf:"bytes,6,opt,name=bin,proto3" json:"bin,omitempty"`
	MerchantId        string                 `protobuf:"bytes,7,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluateFraudRequest) Reset() {
	*x = EvaluateFraudRequest{}
	mi := &file_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFraudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFraudRequest) ProtoMessage() {}

func (x *EvaluateFraudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFraudRequest.ProtoReflect.Descriptor instead.
func (*EvaluateFraudRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateFraudRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *EvaluateFraudRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *EvaluateFraudRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EvaluateFraudRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *EvaluateFraudRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *EvaluateFraudRequest) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *EvaluateFraudRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type EvaluateFraudResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProbabilityScore float32                `protobuf:"fixed32,1,opt,name=probability_score,json=probabilityScore,proto3" json:"probability_score,omitempty"` // 0.0 (safe) to 1.0 (fraud)
	RiskFactors      []string               `protobuf:"bytes,2,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`                  // e.g. ["high_velocity", "ip_distance_anomaly"]
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvaluateFraudResponse) Reset() {
	*x = EvaluateFraudResponse{}
	mi := &file_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFraudResponse) ProtoMessage() {}

func (x *EvaluateFraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFraudResponse.ProtoReflect.Descriptor instead.
func (*EvaluateFraudResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateFraudResponse) GetProbabilityScore() float32 {
	if x != nil {
		return x.ProbabilityScore
	}
	return 0
}

func (x *EvaluateFraudResponse) GetRiskFactors() []string {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

var File_ml_proto protoreflect.FileDescriptor

const file_ml_proto_rawDesc = "" +
	"\n" +
	"\bml.proto\x12\x02ml\"\xec\x01\n" +
	"\x14EvaluateFraudRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12-\n" +
	"\x12device_fingerprint\x18\x02 \x01(\tR\x11deviceFingerprint\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12\x10\n" +
	"\x03bin\x18\x06 \x01(\tR\x03bin\x12\x1f\n" +
	"\vmerchant_id\x18\a \x01(\tR\n" +
	"merchantId\"g\n" +
	"\x15EvaluateFraudResponse\x12+\n" +
	"\x11probability_score\x18\x01 \x01(\x02R\x10probabilityScore\x12!\n" +
	"\frisk_factors\x18\x02 \x03(\tR\vriskFactors2`\n" +
	"\rRiskMLService\x12O\n" +
	"\x18EvaluateFraudProbability\x12\x18.ml.EvaluateFraudRequest\x1a\x19.ml.EvaluateFraudResponseB3Z1payment-gateway/services/risk-service/proto/ml;mlb\x06proto3"

var (
	file_ml_proto_rawDescOnce sync.Once
	file_ml_proto_rawDescData []byte
)

func file_ml_proto_rawDescGZIP() []byte {
	file_ml_proto_rawDescOnce.Do(func() {
		file_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)))
	})
	return file_ml_proto_rawDescData
}

var file_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_proto_goTypes = []any{
	(*EvaluateFraudRequest)(nil),  // 0: ml.EvaluateFraudRequest
	(*EvaluateFraudResponse)(nil), // 1: ml.EvaluateFraudResponse
}
var file_ml_proto_depIdxs = []int32{
	0, // 0: ml.RiskMLService.EvaluateFraudProbability:input_type -> ml.EvaluateFraudRequest
	1, // 1: ml.RiskMLService.EvaluateFraudProbability:output_type -> ml.EvaluateFraudResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_proto_init() }
func file_ml_proto_init() {
	if File_ml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_proto_goTypes,
		DependencyIndexes: file_ml_proto_depIdxs,
		MessageInfos:      file_ml_proto_msgTypes,
	}.Build()
	File_ml_proto = out.File
	file_ml_proto_goTypes = nil
	file_ml_proto_depIdxs = nil
}
