// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ml.proto

package ml

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskMLService_EvaluateFraudProbability_FullMethodName = "/ml.RiskMLService/EvaluateFraudProbability"
)

// RiskMLServiceClient is the client API for RiskMLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The RiskMLService provides predictive ML scoring (TensorFlow/XGBoost)
type RiskMLServiceClient interface {
	EvaluateFraudProbability(ctx context.Context, in *EvaluateFraudRequest, opts ...grpc.CallOption) (*EvaluateFraudResponse, error)
}

type riskMLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskMLServiceClient(cc grpc.ClientConnInterface) RiskMLServiceClient {
	return &riskMLServiceClient{cc}
}

func (c *riskMLServiceClient) EvaluateFraudProbability(ctx context.Context, in *EvaluateFraudRequest, opts ...grpc.CallOption) (*EvaluateFraudResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateFraudResponse)
	err := c.cc.Invoke(ctx, RiskMLService_EvaluateFraudProbability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskMLServiceServer is the server API for RiskMLService service.
// All implementations must embed UnimplementedRiskMLServiceServer
// for forward compatibility.
//
// The RiskMLService provides predictive ML scoring (TensorFlow/XGBoost)
type RiskMLServiceServer interface {
	EvaluateFraudProbability(context.Context, *EvaluateFraudRequest) (*EvaluateFraudResponse, error)
	mustEmbedUnimplementedRiskMLServiceServer()
}

// UnimplementedRiskMLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskMLServiceServer struct{}

func (UnimplementedRiskMLServiceServer) EvaluateFraudProbability(context.Context, *EvaluateFraudRequest) (*EvaluateFraudResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateFraudProbability not implemented")
}
func (UnimplementedRiskMLServiceServer) mustEmbedUnimplementedRiskMLServiceServer() {}
func (UnimplementedRiskMLServiceServer) testEmbeddedByValue()                       {}

// UnsafeRiskMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskMLServiceServer will
// result in compilation errors.
type UnsafeRiskMLServiceServer interface {
	mustEmbedUnimplementedRiskMLServiceServer()
}

func RegisterRiskMLServiceServer(s grpc.ServiceRegistrar, srv RiskMLServiceServer) {
	// If the following call panics, it indicates UnimplementedRiskMLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskMLService_ServiceDesc, srv)
}

func _RiskMLService_EvaluateFraudProbability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateFraudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskMLServiceServer).EvaluateFraudProbability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskMLService_EvaluateFraudProbability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskMLServiceServer).EvaluateFraudProbability(ctx, req.(*EvaluateFraudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskMLService_ServiceDesc is the grpc.ServiceDesc for RiskMLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskMLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ml.RiskMLService",
	HandlerType: (*RiskMLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateFraudProbability",
			Handler:    _RiskMLService_EvaluateFraudProbability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml.proto",
}
