// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: settlement_read.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettlementReadService_GetSettlements_FullMethodName = "/settlement_read.SettlementReadService/GetSettlements"
)

// SettlementReadServiceClient is the client API for SettlementReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettlementReadServiceClient interface {
	GetSettlements(ctx context.Context, in *GetSettlementsRequest, opts ...grpc.CallOption) (*GetSettlementsResponse, error)
}

type settlementReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlementReadServiceClient(cc grpc.ClientConnInterface) SettlementReadServiceClient {
	return &settlementReadServiceClient{cc}
}

func (c *settlementReadServiceClient) GetSettlements(ctx context.Context, in *GetSettlementsRequest, opts ...grpc.CallOption) (*GetSettlementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettlementsResponse)
	err := c.cc.Invoke(ctx, SettlementReadService_GetSettlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettlementReadServiceServer is the server API for SettlementReadService service.
// All implementations must embed UnimplementedSettlementReadServiceServer
// for forward compatibility.
type SettlementReadServiceServer interface {
	GetSettlements(context.Context, *GetSettlementsRequest) (*GetSettlementsResponse, error)
	mustEmbedUnimplementedSettlementReadServiceServer()
}

// UnimplementedSettlementReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettlementReadServiceServer struct{}

func (UnimplementedSettlementReadServiceServer) GetSettlements(context.Context, *GetSettlementsRequest) (*GetSettlementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettlements not implemented")
}
func (UnimplementedSettlementReadServiceServer) mustEmbedUnimplementedSettlementReadServiceServer() {}
func (UnimplementedSettlementReadServiceServer) testEmbeddedByValue()                               {}

// UnsafeSettlementReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettlementReadServiceServer will
// result in compilation errors.
type UnsafeSettlementReadServiceServer interface {
	mustEmbedUnimplementedSettlementReadServiceServer()
}

func RegisterSettlementReadServiceServer(s grpc.ServiceRegistrar, srv SettlementReadServiceServer) {
	// If the following call panics, it indicates UnimplementedSettlementReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettlementReadService_ServiceDesc, srv)
}

func _SettlementReadService_GetSettlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementReadServiceServer).GetSettlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementReadService_GetSettlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementReadServiceServer).GetSettlements(ctx, req.(*GetSettlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettlementReadService_ServiceDesc is the grpc.ServiceDesc for SettlementReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettlementReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settlement_read.SettlementReadService",
	HandlerType: (*SettlementReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSettlements",
			Handler:    _SettlementReadService_GetSettlements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settlement_read.proto",
}
