// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ledger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_RecordJournalEntry_FullMethodName           = "/ledger.LedgerService/RecordJournalEntry"
	LedgerService_GetLedgerEntriesByReferences_FullMethodName = "/ledger.LedgerService/GetLedgerEntriesByReferences"
	LedgerService_ReserveFunds_FullMethodName                 = "/ledger.LedgerService/ReserveFunds"
	LedgerService_ReleaseReservedFunds_FullMethodName         = "/ledger.LedgerService/ReleaseReservedFunds"
	LedgerService_CompleteSettlement_FullMethodName           = "/ledger.LedgerService/CompleteSettlement"
	LedgerService_GetLedgerBalances_FullMethodName            = "/ledger.LedgerService/GetLedgerBalances"
	LedgerService_GetLedgerEntriesPaginated_FullMethodName    = "/ledger.LedgerService/GetLedgerEntriesPaginated"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	RecordJournalEntry(ctx context.Context, in *RecordJournalEntryRequest, opts ...grpc.CallOption) (*RecordJournalEntryResponse, error)
	GetLedgerEntriesByReferences(ctx context.Context, in *GetLedgerEntriesRequest, opts ...grpc.CallOption) (*GetLedgerEntriesResponse, error)
	// Settlement Financial Operations
	ReserveFunds(ctx context.Context, in *ReserveFundsRequest, opts ...grpc.CallOption) (*ReserveFundsResponse, error)
	ReleaseReservedFunds(ctx context.Context, in *ReleaseReservedFundsRequest, opts ...grpc.CallOption) (*ReleaseReservedFundsResponse, error)
	CompleteSettlement(ctx context.Context, in *CompleteSettlementRequest, opts ...grpc.CallOption) (*CompleteSettlementResponse, error)
	// BFF Read APIs — caller MUST provide valid RequestContext with merchant_id
	GetLedgerBalances(ctx context.Context, in *GetLedgerBalancesRequest, opts ...grpc.CallOption) (*GetLedgerBalancesResponse, error)
	GetLedgerEntriesPaginated(ctx context.Context, in *GetLedgerEntriesPaginatedRequest, opts ...grpc.CallOption) (*GetLedgerEntriesPaginatedResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) RecordJournalEntry(ctx context.Context, in *RecordJournalEntryRequest, opts ...grpc.CallOption) (*RecordJournalEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordJournalEntryResponse)
	err := c.cc.Invoke(ctx, LedgerService_RecordJournalEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgerEntriesByReferences(ctx context.Context, in *GetLedgerEntriesRequest, opts ...grpc.CallOption) (*GetLedgerEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerEntriesResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgerEntriesByReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReserveFunds(ctx context.Context, in *ReserveFundsRequest, opts ...grpc.CallOption) (*ReserveFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveFundsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReserveFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReleaseReservedFunds(ctx context.Context, in *ReleaseReservedFundsRequest, opts ...grpc.CallOption) (*ReleaseReservedFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseReservedFundsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReleaseReservedFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) CompleteSettlement(ctx context.Context, in *CompleteSettlementRequest, opts ...grpc.CallOption) (*CompleteSettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteSettlementResponse)
	err := c.cc.Invoke(ctx, LedgerService_CompleteSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgerBalances(ctx context.Context, in *GetLedgerBalancesRequest, opts ...grpc.CallOption) (*GetLedgerBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerBalancesResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgerBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgerEntriesPaginated(ctx context.Context, in *GetLedgerEntriesPaginatedRequest, opts ...grpc.CallOption) (*GetLedgerEntriesPaginatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerEntriesPaginatedResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgerEntriesPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	RecordJournalEntry(context.Context, *RecordJournalEntryRequest) (*RecordJournalEntryResponse, error)
	GetLedgerEntriesByReferences(context.Context, *GetLedgerEntriesRequest) (*GetLedgerEntriesResponse, error)
	// Settlement Financial Operations
	ReserveFunds(context.Context, *ReserveFundsRequest) (*ReserveFundsResponse, error)
	ReleaseReservedFunds(context.Context, *ReleaseReservedFundsRequest) (*ReleaseReservedFundsResponse, error)
	CompleteSettlement(context.Context, *CompleteSettlementRequest) (*CompleteSettlementResponse, error)
	// BFF Read APIs — caller MUST provide valid RequestContext with merchant_id
	GetLedgerBalances(context.Context, *GetLedgerBalancesRequest) (*GetLedgerBalancesResponse, error)
	GetLedgerEntriesPaginated(context.Context, *GetLedgerEntriesPaginatedRequest) (*GetLedgerEntriesPaginatedResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) RecordJournalEntry(context.Context, *RecordJournalEntryRequest) (*RecordJournalEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordJournalEntry not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgerEntriesByReferences(context.Context, *GetLedgerEntriesRequest) (*GetLedgerEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerEntriesByReferences not implemented")
}
func (UnimplementedLedgerServiceServer) ReserveFunds(context.Context, *ReserveFundsRequest) (*ReserveFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveFunds not implemented")
}
func (UnimplementedLedgerServiceServer) ReleaseReservedFunds(context.Context, *ReleaseReservedFundsRequest) (*ReleaseReservedFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseReservedFunds not implemented")
}
func (UnimplementedLedgerServiceServer) CompleteSettlement(context.Context, *CompleteSettlementRequest) (*CompleteSettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteSettlement not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgerBalances(context.Context, *GetLedgerBalancesRequest) (*GetLedgerBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerBalances not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgerEntriesPaginated(context.Context, *GetLedgerEntriesPaginatedRequest) (*GetLedgerEntriesPaginatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerEntriesPaginated not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_RecordJournalEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).RecordJournalEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_RecordJournalEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).RecordJournalEntry(ctx, req.(*RecordJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgerEntriesByReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgerEntriesByReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgerEntriesByReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgerEntriesByReferences(ctx, req.(*GetLedgerEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReserveFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReserveFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReserveFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReserveFunds(ctx, req.(*ReserveFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReleaseReservedFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseReservedFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReleaseReservedFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReleaseReservedFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReleaseReservedFunds(ctx, req.(*ReleaseReservedFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_CompleteSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CompleteSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CompleteSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CompleteSettlement(ctx, req.(*CompleteSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgerBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgerBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgerBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgerBalances(ctx, req.(*GetLedgerBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgerEntriesPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerEntriesPaginatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgerEntriesPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgerEntriesPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgerEntriesPaginated(ctx, req.(*GetLedgerEntriesPaginatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordJournalEntry",
			Handler:    _LedgerService_RecordJournalEntry_Handler,
		},
		{
			MethodName: "GetLedgerEntriesByReferences",
			Handler:    _LedgerService_GetLedgerEntriesByReferences_Handler,
		},
		{
			MethodName: "ReserveFunds",
			Handler:    _LedgerService_ReserveFunds_Handler,
		},
		{
			MethodName: "ReleaseReservedFunds",
			Handler:    _LedgerService_ReleaseReservedFunds_Handler,
		},
		{
			MethodName: "CompleteSettlement",
			Handler:    _LedgerService_CompleteSettlement_Handler,
		},
		{
			MethodName: "GetLedgerBalances",
			Handler:    _LedgerService_GetLedgerBalances_Handler,
		},
		{
			MethodName: "GetLedgerEntriesPaginated",
			Handler:    _LedgerService_GetLedgerEntriesPaginated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger.proto",
}
