// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: webhook_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplayWebhookDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayWebhookDeliveryRequest) Reset() {
	*x = ReplayWebhookDeliveryRequest{}
	mi := &file_webhook_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayWebhookDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayWebhookDeliveryRequest) ProtoMessage() {}

func (x *ReplayWebhookDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayWebhookDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ReplayWebhookDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_webhook_read_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayWebhookDeliveryRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ReplayWebhookDeliveryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type ReplayWebhookDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayWebhookDeliveryResponse) Reset() {
	*x = ReplayWebhookDeliveryResponse{}
	mi := &file_webhook_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayWebhookDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayWebhookDeliveryResponse) ProtoMessage() {}

func (x *ReplayWebhookDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayWebhookDeliveryResponse.ProtoReflect.Descriptor instead.
func (*ReplayWebhookDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_webhook_read_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayWebhookDeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplayWebhookDeliveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWebhookDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookDeliveriesRequest) Reset() {
	*x = GetWebhookDeliveriesRequest{}
	mi := &file_webhook_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookDeliveriesRequest) ProtoMessage() {}

func (x *GetWebhookDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_webhook_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetWebhookDeliveriesRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetWebhookDeliveriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWebhookDeliveriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type WebhookDelivery struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId         string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	EventId            string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType          string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AttemptCount       int32                  `protobuf:"varint,6,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	ResponseStatusCode int32                  `protobuf:"varint,7,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	ResponseBody       string                 `protobuf:"bytes,8,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	NextRetryAt        string                 `protobuf:"bytes,10,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	LastError          string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Payload            string                 `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebhookDelivery) Reset() {
	*x = WebhookDelivery{}
	mi := &file_webhook_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDelivery) ProtoMessage() {}

func (x *WebhookDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDelivery.ProtoReflect.Descriptor instead.
func (*WebhookDelivery) Descriptor() ([]byte, []int) {
	return file_webhook_read_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookDelivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookDelivery) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *WebhookDelivery) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WebhookDelivery) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WebhookDelivery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookDelivery) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *WebhookDelivery) GetResponseStatusCode() int32 {
	if x != nil {
		return x.ResponseStatusCode
	}
	return 0
}

func (x *WebhookDelivery) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *WebhookDelivery) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WebhookDelivery) GetNextRetryAt() string {
	if x != nil {
		return x.NextRetryAt
	}
	return ""
}

func (x *WebhookDelivery) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *WebhookDelivery) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GetWebhookDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*WebhookDelivery     `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookDeliveriesResponse) Reset() {
	*x = GetWebhookDeliveriesResponse{}
	mi := &file_webhook_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookDeliveriesResponse) ProtoMessage() {}

func (x *GetWebhookDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_webhook_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetWebhookDeliveriesResponse) GetDeliveries() []*WebhookDelivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *GetWebhookDeliveriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_webhook_read_proto protoreflect.FileDescriptor

const file_webhook_read_proto_rawDesc = "" +
	"\n" +
	"\x12webhook_read.proto\x12\fwebhook_read\"`\n" +
	"\x1cReplayWebhookDeliveryRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\"S\n" +
	"\x1dReplayWebhookDeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"l\n" +
	"\x1bGetWebhookDeliveriesRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8c\x03\n" +
	"\x0fWebhookDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rattempt_count\x18\x06 \x01(\x05R\fattemptCount\x120\n" +
	"\x14response_status_code\x18\a \x01(\x05R\x12responseStatusCode\x12#\n" +
	"\rresponse_body\x18\b \x01(\tR\fresponseBody\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\"\n" +
	"\rnext_retry_at\x18\n" +
	" \x01(\tR\vnextRetryAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x12\x18\n" +
	"\apayload\x18\f \x01(\tR\apayload\"s\n" +
	"\x1cGetWebhookDeliveriesResponse\x12=\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1d.webhook_read.WebhookDeliveryR\n" +
	"deliveries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xf5\x01\n" +
	"\x12WebhookReadService\x12m\n" +
	"\x14GetWebhookDeliveries\x12).webhook_read.GetWebhookDeliveriesRequest\x1a*.webhook_read.GetWebhookDeliveriesResponse\x12p\n" +
	"\x15ReplayWebhookDelivery\x12*.webhook_read.ReplayWebhookDeliveryRequest\x1a+.webhook_read.ReplayWebhookDeliveryResponseB'Z%payment-gateway/webhook-service/protob\x06proto3"

var (
	file_webhook_read_proto_rawDescOnce sync.Once
	file_webhook_read_proto_rawDescData []byte
)

func file_webhook_read_proto_rawDescGZIP() []byte {
	file_webhook_read_proto_rawDescOnce.Do(func() {
		file_webhook_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_read_proto_rawDesc), len(file_webhook_read_proto_rawDesc)))
	})
	return file_webhook_read_proto_rawDescData
}

var file_webhook_read_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_webhook_read_proto_goTypes = []any{
	(*ReplayWebhookDeliveryRequest)(nil),  // 0: webhook_read.ReplayWebhookDeliveryRequest
	(*ReplayWebhookDeliveryResponse)(nil), // 1: webhook_read.ReplayWebhookDeliveryResponse
	(*GetWebhookDeliveriesRequest)(nil),   // 2: webhook_read.GetWebhookDeliveriesRequest
	(*WebhookDelivery)(nil),               // 3: webhook_read.WebhookDelivery
	(*GetWebhookDeliveriesResponse)(nil),  // 4: webhook_read.GetWebhookDeliveriesResponse
}
var file_webhook_read_proto_depIdxs = []int32{
	3, // 0: webhook_read.GetWebhookDeliveriesResponse.deliveries:type_name -> webhook_read.WebhookDelivery
	2, // 1: webhook_read.WebhookReadService.GetWebhookDeliveries:input_type -> webhook_read.GetWebhookDeliveriesRequest
	0, // 2: webhook_read.WebhookReadService.ReplayWebhookDelivery:input_type -> webhook_read.ReplayWebhookDeliveryRequest
	4, // 3: webhook_read.WebhookReadService.GetWebhookDeliveries:output_type -> webhook_read.GetWebhookDeliveriesResponse
	1, // 4: webhook_read.WebhookReadService.ReplayWebhookDelivery:output_type -> webhook_read.ReplayWebhookDeliveryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webhook_read_proto_init() }
func file_webhook_read_proto_init() {
	if File_webhook_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_read_proto_rawDesc), len(file_webhook_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhook_read_proto_goTypes,
		DependencyIndexes: file_webhook_read_proto_depIdxs,
		MessageInfos:      file_webhook_read_proto_msgTypes,
	}.Build()
	File_webhook_read_proto = out.File
	file_webhook_read_proto_goTypes = nil
	file_webhook_read_proto_depIdxs = nil
}
