// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: notification_read.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationReadService_GetNotifications_FullMethodName = "/notification_read.NotificationReadService/GetNotifications"
)

// NotificationReadServiceClient is the client API for NotificationReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationReadServiceClient interface {
	GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error)
}

type notificationReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationReadServiceClient(cc grpc.ClientConnInterface) NotificationReadServiceClient {
	return &notificationReadServiceClient{cc}
}

func (c *notificationReadServiceClient) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationReadService_GetNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationReadServiceServer is the server API for NotificationReadService service.
// All implementations must embed UnimplementedNotificationReadServiceServer
// for forward compatibility.
type NotificationReadServiceServer interface {
	GetNotifications(context.Context, *GetNotificationsRequest) (*GetNotificationsResponse, error)
	mustEmbedUnimplementedNotificationReadServiceServer()
}

// UnimplementedNotificationReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationReadServiceServer struct{}

func (UnimplementedNotificationReadServiceServer) GetNotifications(context.Context, *GetNotificationsRequest) (*GetNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedNotificationReadServiceServer) mustEmbedUnimplementedNotificationReadServiceServer() {
}
func (UnimplementedNotificationReadServiceServer) testEmbeddedByValue() {}

// UnsafeNotificationReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationReadServiceServer will
// result in compilation errors.
type UnsafeNotificationReadServiceServer interface {
	mustEmbedUnimplementedNotificationReadServiceServer()
}

func RegisterNotificationReadServiceServer(s grpc.ServiceRegistrar, srv NotificationReadServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationReadService_ServiceDesc, srv)
}

func _NotificationReadService_GetNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationReadServiceServer).GetNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationReadService_GetNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationReadServiceServer).GetNotifications(ctx, req.(*GetNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationReadService_ServiceDesc is the grpc.ServiceDesc for NotificationReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification_read.NotificationReadService",
	HandlerType: (*NotificationReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotifications",
			Handler:    _NotificationReadService_GetNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification_read.proto",
}
