// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notification_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_notification_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_read_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type NotificationLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "EMAIL" or "SMS"
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "SENT", "FAILED", "PENDING"
	ErrorDetails  string                 `protobuf:"bytes,7,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationLog) Reset() {
	*x = NotificationLog{}
	mi := &file_notification_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationLog) ProtoMessage() {}

func (x *NotificationLog) ProtoReflect() protoreflect.Message {
	mi := &file_notification_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationLog.ProtoReflect.Descriptor instead.
func (*NotificationLog) Descriptor() ([]byte, []int) {
	return file_notification_read_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationLog) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *NotificationLog) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationLog) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotificationLog) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationLog) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

func (x *NotificationLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationLog     `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_notification_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationsResponse) GetNotifications() []*NotificationLog {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_notification_read_proto protoreflect.FileDescriptor

const file_notification_read_proto_rawDesc = "" +
	"\n" +
	"\x17notification_read.proto\x12\x11notification_read\"h\n" +
	"\x17GetNotificationsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xea\x01\n" +
	"\x0fNotificationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rerror_details\x18\a \x01(\tR\ferrorDetails\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"z\n" +
	"\x18GetNotificationsResponse\x12H\n" +
	"\rnotifications\x18\x01 \x03(\v2\".notification_read.NotificationLogR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x86\x01\n" +
	"\x17NotificationReadService\x12k\n" +
	"\x10GetNotifications\x12*.notification_read.GetNotificationsRequest\x1a+.notification_read.GetNotificationsResponseB,Z*payment-gateway/notification-service/protob\x06proto3"

var (
	file_notification_read_proto_rawDescOnce sync.Once
	file_notification_read_proto_rawDescData []byte
)

func file_notification_read_proto_rawDescGZIP() []byte {
	file_notification_read_proto_rawDescOnce.Do(func() {
		file_notification_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_read_proto_rawDesc), len(file_notification_read_proto_rawDesc)))
	})
	return file_notification_read_proto_rawDescData
}

var file_notification_read_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notification_read_proto_goTypes = []any{
	(*GetNotificationsRequest)(nil),  // 0: notification_read.GetNotificationsRequest
	(*NotificationLog)(nil),          // 1: notification_read.NotificationLog
	(*GetNotificationsResponse)(nil), // 2: notification_read.GetNotificationsResponse
}
var file_notification_read_proto_depIdxs = []int32{
	1, // 0: notification_read.GetNotificationsResponse.notifications:type_name -> notification_read.NotificationLog
	0, // 1: notification_read.NotificationReadService.GetNotifications:input_type -> notification_read.GetNotificationsRequest
	2, // 2: notification_read.NotificationReadService.GetNotifications:output_type -> notification_read.GetNotificationsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_read_proto_init() }
func file_notification_read_proto_init() {
	if File_notification_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_read_proto_rawDesc), len(file_notification_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_read_proto_goTypes,
		DependencyIndexes: file_notification_read_proto_depIdxs,
		MessageInfos:      file_notification_read_proto_msgTypes,
	}.Build()
	File_notification_read_proto = out.File
	file_notification_read_proto_goTypes = nil
	file_notification_read_proto_depIdxs = nil
}
