# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ml_pb2 as ml__pb2


class RiskMLServiceStub(object):
    """The RiskMLService provides predictive ML scoring (TensorFlow/XGBoost)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateFraudProbability = channel.unary_unary(
                '/ml.RiskMLService/EvaluateFraudProbability',
                request_serializer=ml__pb2.EvaluateFraudRequest.SerializeToString,
                response_deserializer=ml__pb2.EvaluateFraudResponse.FromString,
                )


class RiskMLServiceServicer(object):
    """The RiskMLService provides predictive ML scoring (TensorFlow/XGBoost)
    """

    def EvaluateFraudProbability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateFraudProbability': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateFraudProbability,
                    request_deserializer=ml__pb2.EvaluateFraudRequest.FromString,
                    response_serializer=ml__pb2.EvaluateFraudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.RiskMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RiskMLService(object):
    """The RiskMLService provides predictive ML scoring (TensorFlow/XGBoost)
    """

    @staticmethod
    def EvaluateFraudProbability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.RiskMLService/EvaluateFraudProbability',
            ml__pb2.EvaluateFraudRequest.SerializeToString,
            ml__pb2.EvaluateFraudResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
