# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x02ml\"\x9f\x01\n\x14\x45valuateFraudRequest\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65vice_fingerprint\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x05 \x01(\t\x12\x0b\n\x03\x62in\x18\x06 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x07 \x01(\t\"H\n\x15\x45valuateFraudResponse\x12\x19\n\x11probability_score\x18\x01 \x01(\x02\x12\x14\n\x0crisk_factors\x18\x02 \x03(\t2`\n\rRiskMLService\x12O\n\x18\x45valuateFraudProbability\x12\x18.ml.EvaluateFraudRequest\x1a\x19.ml.EvaluateFraudResponseB3Z1payment-gateway/services/risk-service/proto/ml;mlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1payment-gateway/services/risk-service/proto/ml;ml'
  _globals['_EVALUATEFRAUDREQUEST']._serialized_start=17
  _globals['_EVALUATEFRAUDREQUEST']._serialized_end=176
  _globals['_EVALUATEFRAUDRESPONSE']._serialized_start=178
  _globals['_EVALUATEFRAUDRESPONSE']._serialized_end=250
  _globals['_RISKMLSERVICE']._serialized_start=252
  _globals['_RISKMLSERVICE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
