// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: payment_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                      // Optional: filter by status string
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                                  // Optional: filter by currency
	FromCreatedAt string                 `protobuf:"bytes,3,opt,name=from_created_at,json=fromCreatedAt,proto3" json:"from_created_at,omitempty"` // ISO8601 lower bound
	ToCreatedAt   string                 `protobuf:"bytes,4,opt,name=to_created_at,json=toCreatedAt,proto3" json:"to_created_at,omitempty"`       // ISO8601 upper bound
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFilter) Reset() {
	*x = PaymentFilter{}
	mi := &file_payment_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFilter) ProtoMessage() {}

func (x *PaymentFilter) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFilter.ProtoReflect.Descriptor instead.
func (*PaymentFilter) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentFilter) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentFilter) GetFromCreatedAt() string {
	if x != nil {
		return x.FromCreatedAt
	}
	return ""
}

func (x *PaymentFilter) GetToCreatedAt() string {
	if x != nil {
		return x.ToCreatedAt
	}
	return ""
}

type GetPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Must match RequestContext.merchant_id
	Filter        *PaymentFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	AfterCursor   string                 `protobuf:"bytes,3,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"` // Cursor-based pagination
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                               // Max results; server-side ceiling enforced
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsRequest) Reset() {
	*x = GetPaymentsRequest{}
	mi := &file_payment_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsRequest) ProtoMessage() {}

func (x *GetPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetPaymentsRequest) GetFilter() *PaymentFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetPaymentsRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

func (x *GetPaymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaymentSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentId         string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount            int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId        string                 `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MerchantReference string                 `protobuf:"bytes,9,opt,name=merchant_reference,json=merchantReference,proto3" json:"merchant_reference,omitempty"`
	RefundedAmount    int64                  `protobuf:"varint,10,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentSummary) Reset() {
	*x = PaymentSummary{}
	mi := &file_payment_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSummary) ProtoMessage() {}

func (x *PaymentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSummary.ProtoReflect.Descriptor instead.
func (*PaymentSummary) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentSummary) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentSummary) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentSummary) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentSummary) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PaymentSummary) GetMerchantReference() string {
	if x != nil {
		return x.MerchantReference
	}
	return ""
}

func (x *PaymentSummary) GetRefundedAmount() int64 {
	if x != nil {
		return x.RefundedAmount
	}
	return 0
}

type GetPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentSummary      `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse) Reset() {
	*x = GetPaymentsResponse{}
	mi := &file_payment_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse) ProtoMessage() {}

func (x *GetPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentsResponse) GetPayments() []*PaymentSummary {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetPaymentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetPaymentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Must match RequestContext.merchant_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentSummary        `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_payment_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentResponse) GetPayment() *PaymentSummary {
	if x != nil {
		return x.Payment
	}
	return nil
}

type StatusHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RecordedAt    string                 `protobuf:"bytes,3,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusHistoryEntry) Reset() {
	*x = StatusHistoryEntry{}
	mi := &file_payment_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusHistoryEntry) ProtoMessage() {}

func (x *StatusHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusHistoryEntry.ProtoReflect.Descriptor instead.
func (*StatusHistoryEntry) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{6}
}

func (x *StatusHistoryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusHistoryEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StatusHistoryEntry) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

type GetPaymentStatusHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Must match RequestContext.merchant_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusHistoryRequest) Reset() {
	*x = GetPaymentStatusHistoryRequest{}
	mi := &file_payment_read_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusHistoryRequest) ProtoMessage() {}

func (x *GetPaymentStatusHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusHistoryRequest) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentStatusHistoryRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentStatusHistoryRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetPaymentStatusHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StatusHistoryEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusHistoryResponse) Reset() {
	*x = GetPaymentStatusHistoryResponse{}
	mi := &file_payment_read_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusHistoryResponse) ProtoMessage() {}

func (x *GetPaymentStatusHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusHistoryResponse) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentStatusHistoryResponse) GetEntries() []*StatusHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetRefundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // Optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundsRequest) Reset() {
	*x = GetRefundsRequest{}
	mi := &file_payment_read_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundsRequest) ProtoMessage() {}

func (x *GetRefundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundsRequest.ProtoReflect.Descriptor instead.
func (*GetRefundsRequest) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{9}
}

func (x *GetRefundsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetRefundsRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetRefundsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRefundsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RefundSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundSummary) Reset() {
	*x = RefundSummary{}
	mi := &file_payment_read_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundSummary) ProtoMessage() {}

func (x *RefundSummary) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundSummary.ProtoReflect.Descriptor instead.
func (*RefundSummary) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{10}
}

func (x *RefundSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefundSummary) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundSummary) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RefundSummary) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RefundSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundSummary) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RefundSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetRefundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refunds       []*RefundSummary       `protobuf:"bytes,1,rep,name=refunds,proto3" json:"refunds,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundsResponse) Reset() {
	*x = GetRefundsResponse{}
	mi := &file_payment_read_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundsResponse) ProtoMessage() {}

func (x *GetRefundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_read_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundsResponse.ProtoReflect.Descriptor instead.
func (*GetRefundsResponse) Descriptor() ([]byte, []int) {
	return file_payment_read_proto_rawDescGZIP(), []int{11}
}

func (x *GetRefundsResponse) GetRefunds() []*RefundSummary {
	if x != nil {
		return x.Refunds
	}
	return nil
}

func (x *GetRefundsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_payment_read_proto protoreflect.FileDescriptor

const file_payment_read_proto_rawDesc = "" +
	"\n" +
	"\x12payment_read.proto\x12\fpayment_read\"\x8f\x01\n" +
	"\rPaymentFilter\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12&\n" +
	"\x0ffrom_created_at\x18\x03 \x01(\tR\rfromCreatedAt\x12\"\n" +
	"\rto_created_at\x18\x04 \x01(\tR\vtoCreatedAt\"\xa3\x01\n" +
	"\x12GetPaymentsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x123\n" +
	"\x06filter\x18\x02 \x01(\v2\x1b.payment_read.PaymentFilterR\x06filter\x12!\n" +
	"\fafter_cursor\x18\x03 \x01(\tR\vafterCursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xd9\x02\n" +
	"\x0ePaymentSummary\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\tR\n" +
	"customerId\x12-\n" +
	"\x12merchant_reference\x18\t \x01(\tR\x11merchantReference\x12'\n" +
	"\x0frefunded_amount\x18\n" +
	" \x01(\x03R\x0erefundedAmount\"\x8b\x01\n" +
	"\x13GetPaymentsResponse\x128\n" +
	"\bpayments\x18\x01 \x03(\v2\x1c.payment_read.PaymentSummaryR\bpayments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"S\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"L\n" +
	"\x12GetPaymentResponse\x126\n" +
	"\apayment\x18\x01 \x01(\v2\x1c.payment_read.PaymentSummaryR\apayment\"e\n" +
	"\x12StatusHistoryEntry\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vrecorded_at\x18\x03 \x01(\tR\n" +
	"recordedAt\"`\n" +
	"\x1eGetPaymentStatusHistoryRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"]\n" +
	"\x1fGetPaymentStatusHistoryResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .payment_read.StatusHistoryEntryR\aentries\"\x81\x01\n" +
	"\x11GetRefundsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x81\x02\n" +
	"\rRefundSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"a\n" +
	"\x12GetRefundsResponse\x125\n" +
	"\arefunds\x18\x01 \x03(\v2\x1b.payment_read.RefundSummaryR\arefunds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x82\x03\n" +
	"\x12PaymentReadService\x12R\n" +
	"\vGetPayments\x12 .payment_read.GetPaymentsRequest\x1a!.payment_read.GetPaymentsResponse\x12O\n" +
	"\n" +
	"GetPayment\x12\x1f.payment_read.GetPaymentRequest\x1a .payment_read.GetPaymentResponse\x12v\n" +
	"\x17GetPaymentStatusHistory\x12,.payment_read.GetPaymentStatusHistoryRequest\x1a-.payment_read.GetPaymentStatusHistoryResponse\x12O\n" +
	"\n" +
	"GetRefunds\x12\x1f.payment_read.GetRefundsRequest\x1a .payment_read.GetRefundsResponseB-Z+payment-gateway/payment-service/proto;protob\x06proto3"

var (
	file_payment_read_proto_rawDescOnce sync.Once
	file_payment_read_proto_rawDescData []byte
)

func file_payment_read_proto_rawDescGZIP() []byte {
	file_payment_read_proto_rawDescOnce.Do(func() {
		file_payment_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_read_proto_rawDesc), len(file_payment_read_proto_rawDesc)))
	})
	return file_payment_read_proto_rawDescData
}

var file_payment_read_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_payment_read_proto_goTypes = []any{
	(*PaymentFilter)(nil),                   // 0: payment_read.PaymentFilter
	(*GetPaymentsRequest)(nil),              // 1: payment_read.GetPaymentsRequest
	(*PaymentSummary)(nil),                  // 2: payment_read.PaymentSummary
	(*GetPaymentsResponse)(nil),             // 3: payment_read.GetPaymentsResponse
	(*GetPaymentRequest)(nil),               // 4: payment_read.GetPaymentRequest
	(*GetPaymentResponse)(nil),              // 5: payment_read.GetPaymentResponse
	(*StatusHistoryEntry)(nil),              // 6: payment_read.StatusHistoryEntry
	(*GetPaymentStatusHistoryRequest)(nil),  // 7: payment_read.GetPaymentStatusHistoryRequest
	(*GetPaymentStatusHistoryResponse)(nil), // 8: payment_read.GetPaymentStatusHistoryResponse
	(*GetRefundsRequest)(nil),               // 9: payment_read.GetRefundsRequest
	(*RefundSummary)(nil),                   // 10: payment_read.RefundSummary
	(*GetRefundsResponse)(nil),              // 11: payment_read.GetRefundsResponse
}
var file_payment_read_proto_depIdxs = []int32{
	0,  // 0: payment_read.GetPaymentsRequest.filter:type_name -> payment_read.PaymentFilter
	2,  // 1: payment_read.GetPaymentsResponse.payments:type_name -> payment_read.PaymentSummary
	2,  // 2: payment_read.GetPaymentResponse.payment:type_name -> payment_read.PaymentSummary
	6,  // 3: payment_read.GetPaymentStatusHistoryResponse.entries:type_name -> payment_read.StatusHistoryEntry
	10, // 4: payment_read.GetRefundsResponse.refunds:type_name -> payment_read.RefundSummary
	1,  // 5: payment_read.PaymentReadService.GetPayments:input_type -> payment_read.GetPaymentsRequest
	4,  // 6: payment_read.PaymentReadService.GetPayment:input_type -> payment_read.GetPaymentRequest
	7,  // 7: payment_read.PaymentReadService.GetPaymentStatusHistory:input_type -> payment_read.GetPaymentStatusHistoryRequest
	9,  // 8: payment_read.PaymentReadService.GetRefunds:input_type -> payment_read.GetRefundsRequest
	3,  // 9: payment_read.PaymentReadService.GetPayments:output_type -> payment_read.GetPaymentsResponse
	5,  // 10: payment_read.PaymentReadService.GetPayment:output_type -> payment_read.GetPaymentResponse
	8,  // 11: payment_read.PaymentReadService.GetPaymentStatusHistory:output_type -> payment_read.GetPaymentStatusHistoryResponse
	11, // 12: payment_read.PaymentReadService.GetRefunds:output_type -> payment_read.GetRefundsResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_payment_read_proto_init() }
func file_payment_read_proto_init() {
	if File_payment_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_read_proto_rawDesc), len(file_payment_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_read_proto_goTypes,
		DependencyIndexes: file_payment_read_proto_depIdxs,
		MessageInfos:      file_payment_read_proto_msgTypes,
	}.Build()
	File_payment_read_proto = out.File
	file_payment_read_proto_goTypes = nil
	file_payment_read_proto_depIdxs = nil
}
