// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: payment_write.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentWriteService_ExecutePayment_FullMethodName = "/payment_write.PaymentWriteService/ExecutePayment"
)

// PaymentWriteServiceClient is the client API for PaymentWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentWriteServiceClient interface {
	ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error)
}

type paymentWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentWriteServiceClient(cc grpc.ClientConnInterface) PaymentWriteServiceClient {
	return &paymentWriteServiceClient{cc}
}

func (c *paymentWriteServiceClient) ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentWriteService_ExecutePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentWriteServiceServer is the server API for PaymentWriteService service.
// All implementations must embed UnimplementedPaymentWriteServiceServer
// for forward compatibility.
type PaymentWriteServiceServer interface {
	ExecutePayment(context.Context, *ExecutePaymentRequest) (*ExecutePaymentResponse, error)
	mustEmbedUnimplementedPaymentWriteServiceServer()
}

// UnimplementedPaymentWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentWriteServiceServer struct{}

func (UnimplementedPaymentWriteServiceServer) ExecutePayment(context.Context, *ExecutePaymentRequest) (*ExecutePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePayment not implemented")
}
func (UnimplementedPaymentWriteServiceServer) mustEmbedUnimplementedPaymentWriteServiceServer() {}
func (UnimplementedPaymentWriteServiceServer) testEmbeddedByValue()                             {}

// UnsafePaymentWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentWriteServiceServer will
// result in compilation errors.
type UnsafePaymentWriteServiceServer interface {
	mustEmbedUnimplementedPaymentWriteServiceServer()
}

func RegisterPaymentWriteServiceServer(s grpc.ServiceRegistrar, srv PaymentWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentWriteService_ServiceDesc, srv)
}

func _PaymentWriteService_ExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentWriteServiceServer).ExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentWriteService_ExecutePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentWriteServiceServer).ExecutePayment(ctx, req.(*ExecutePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentWriteService_ServiceDesc is the grpc.ServiceDesc for PaymentWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_write.PaymentWriteService",
	HandlerType: (*PaymentWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePayment",
			Handler:    _PaymentWriteService_ExecutePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_write.proto",
}
