// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: settlement_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSettlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementsRequest) Reset() {
	*x = GetSettlementsRequest{}
	mi := &file_settlement_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementsRequest) ProtoMessage() {}

func (x *GetSettlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementsRequest.ProtoReflect.Descriptor instead.
func (*GetSettlementsRequest) Descriptor() ([]byte, []int) {
	return file_settlement_read_proto_rawDescGZIP(), []int{0}
}

func (x *GetSettlementsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetSettlementsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSettlementsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Settlement struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId         string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount             int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DestinationAccount string                 `protobuf:"bytes,6,opt,name=destination_account,json=destinationAccount,proto3" json:"destination_account,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Settlement) Reset() {
	*x = Settlement{}
	mi := &file_settlement_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settlement) ProtoMessage() {}

func (x *Settlement) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settlement.ProtoReflect.Descriptor instead.
func (*Settlement) Descriptor() ([]byte, []int) {
	return file_settlement_read_proto_rawDescGZIP(), []int{1}
}

func (x *Settlement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Settlement) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Settlement) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Settlement) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Settlement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Settlement) GetDestinationAccount() string {
	if x != nil {
		return x.DestinationAccount
	}
	return ""
}

func (x *Settlement) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Settlement) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSettlementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settlements   []*Settlement          `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementsResponse) Reset() {
	*x = GetSettlementsResponse{}
	mi := &file_settlement_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementsResponse) ProtoMessage() {}

func (x *GetSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementsResponse.ProtoReflect.Descriptor instead.
func (*GetSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_settlement_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetSettlementsResponse) GetSettlements() []*Settlement {
	if x != nil {
		return x.Settlements
	}
	return nil
}

func (x *GetSettlementsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_settlement_read_proto protoreflect.FileDescriptor

const file_settlement_read_proto_rawDesc = "" +
	"\n" +
	"\x15settlement_read.proto\x12\x0fsettlement_read\"f\n" +
	"\x15GetSettlementsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xf8\x01\n" +
	"\n" +
	"Settlement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12/\n" +
	"\x13destination_account\x18\x06 \x01(\tR\x12destinationAccount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"m\n" +
	"\x16GetSettlementsResponse\x12=\n" +
	"\vsettlements\x18\x01 \x03(\v2\x1b.settlement_read.SettlementR\vsettlements\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2z\n" +
	"\x15SettlementReadService\x12a\n" +
	"\x0eGetSettlements\x12&.settlement_read.GetSettlementsRequest\x1a'.settlement_read.GetSettlementsResponseB0Z.payment-gateway/settlement-service/proto;protob\x06proto3"

var (
	file_settlement_read_proto_rawDescOnce sync.Once
	file_settlement_read_proto_rawDescData []byte
)

func file_settlement_read_proto_rawDescGZIP() []byte {
	file_settlement_read_proto_rawDescOnce.Do(func() {
		file_settlement_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_read_proto_rawDesc), len(file_settlement_read_proto_rawDesc)))
	})
	return file_settlement_read_proto_rawDescData
}

var file_settlement_read_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_settlement_read_proto_goTypes = []any{
	(*GetSettlementsRequest)(nil),  // 0: settlement_read.GetSettlementsRequest
	(*Settlement)(nil),             // 1: settlement_read.Settlement
	(*GetSettlementsResponse)(nil), // 2: settlement_read.GetSettlementsResponse
}
var file_settlement_read_proto_depIdxs = []int32{
	1, // 0: settlement_read.GetSettlementsResponse.settlements:type_name -> settlement_read.Settlement
	0, // 1: settlement_read.SettlementReadService.GetSettlements:input_type -> settlement_read.GetSettlementsRequest
	2, // 2: settlement_read.SettlementReadService.GetSettlements:output_type -> settlement_read.GetSettlementsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settlement_read_proto_init() }
func file_settlement_read_proto_init() {
	if File_settlement_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_read_proto_rawDesc), len(file_settlement_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_read_proto_goTypes,
		DependencyIndexes: file_settlement_read_proto_depIdxs,
		MessageInfos:      file_settlement_read_proto_msgTypes,
	}.Build()
	File_settlement_read_proto = out.File
	file_settlement_read_proto_goTypes = nil
	file_settlement_read_proto_depIdxs = nil
}
