// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fx.proto

package fx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExchangeRateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceCurrency string                 `protobuf:"bytes,1,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"` // e.g. USD
	TargetCurrency string                 `protobuf:"bytes,2,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"` // e.g. EUR
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_fx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{0}
}

func (x *GetExchangeRateRequest) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

func (x *GetExchangeRateRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

type GetExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`          // e.g. 0.92
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp of the rate
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`    // Source of the rate (e.g. "bloomberg", "fixer")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateResponse) Reset() {
	*x = GetExchangeRateResponse{}
	mi := &file_fx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateResponse) ProtoMessage() {}

func (x *GetExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*GetExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{1}
}

func (x *GetExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *GetExchangeRateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetExchangeRateResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type LockExchangeRateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceCurrency string                 `protobuf:"bytes,1,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"`
	TargetCurrency string                 `protobuf:"bytes,2,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // Optional: lock for a specific amount
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockExchangeRateRequest) Reset() {
	*x = LockExchangeRateRequest{}
	mi := &file_fx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockExchangeRateRequest) ProtoMessage() {}

func (x *LockExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*LockExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{2}
}

func (x *LockExchangeRateRequest) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

func (x *LockExchangeRateRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *LockExchangeRateRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type LockExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`           // Unique ID to reference this locked rate during settlement
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`                           // The guaranteed rate
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp when the lock expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockExchangeRateResponse) Reset() {
	*x = LockExchangeRateResponse{}
	mi := &file_fx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockExchangeRateResponse) ProtoMessage() {}

func (x *LockExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*LockExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{3}
}

func (x *LockExchangeRateResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *LockExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *LockExchangeRateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_fx_proto protoreflect.FileDescriptor

const file_fx_proto_rawDesc = "" +
	"\n" +
	"\bfx.proto\x12\x02fx\"j\n" +
	"\x16GetExchangeRateRequest\x12'\n" +
	"\x0fsource_currency\x18\x01 \x01(\tR\x0esourceCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x02 \x01(\tR\x0etargetCurrency\"g\n" +
	"\x17GetExchangeRateResponse\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"\x83\x01\n" +
	"\x17LockExchangeRateRequest\x12'\n" +
	"\x0fsource_currency\x18\x01 \x01(\tR\x0esourceCurrency\x12'\n" +
	"\x0ftarget_currency\x18\x02 \x01(\tR\x0etargetCurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"f\n" +
	"\x18LockExchangeRateResponse\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\xa6\x01\n" +
	"\tFxService\x12J\n" +
	"\x0fGetExchangeRate\x12\x1a.fx.GetExchangeRateRequest\x1a\x1b.fx.GetExchangeRateResponse\x12M\n" +
	"\x10LockExchangeRate\x12\x1b.fx.LockExchangeRateRequest\x1a\x1c.fx.LockExchangeRateResponseB.Z,payment-gateway/services/fx-service/proto;fxb\x06proto3"

var (
	file_fx_proto_rawDescOnce sync.Once
	file_fx_proto_rawDescData []byte
)

func file_fx_proto_rawDescGZIP() []byte {
	file_fx_proto_rawDescOnce.Do(func() {
		file_fx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fx_proto_rawDesc), len(file_fx_proto_rawDesc)))
	})
	return file_fx_proto_rawDescData
}

var file_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fx_proto_goTypes = []any{
	(*GetExchangeRateRequest)(nil),   // 0: fx.GetExchangeRateRequest
	(*GetExchangeRateResponse)(nil),  // 1: fx.GetExchangeRateResponse
	(*LockExchangeRateRequest)(nil),  // 2: fx.LockExchangeRateRequest
	(*LockExchangeRateResponse)(nil), // 3: fx.LockExchangeRateResponse
}
var file_fx_proto_depIdxs = []int32{
	0, // 0: fx.FxService.GetExchangeRate:input_type -> fx.GetExchangeRateRequest
	2, // 1: fx.FxService.LockExchangeRate:input_type -> fx.LockExchangeRateRequest
	1, // 2: fx.FxService.GetExchangeRate:output_type -> fx.GetExchangeRateResponse
	3, // 3: fx.FxService.LockExchangeRate:output_type -> fx.LockExchangeRateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fx_proto_init() }
func file_fx_proto_init() {
	if File_fx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_proto_rawDesc), len(file_fx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_proto_goTypes,
		DependencyIndexes: file_fx_proto_depIdxs,
		MessageInfos:      file_fx_proto_msgTypes,
	}.Build()
	File_fx_proto = out.File
	file_fx_proto_goTypes = nil
	file_fx_proto_depIdxs = nil
}
