// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	FromCreatedAt string                 `protobuf:"bytes,3,opt,name=from_created_at,json=fromCreatedAt,proto3" json:"from_created_at,omitempty"`
	ToCreatedAt   string                 `protobuf:"bytes,4,opt,name=to_created_at,json=toCreatedAt,proto3" json:"to_created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_transaction_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_transaction_read_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionFilter) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *TransactionFilter) GetFromCreatedAt() string {
	if x != nil {
		return x.FromCreatedAt
	}
	return ""
}

func (x *TransactionFilter) GetToCreatedAt() string {
	if x != nil {
		return x.ToCreatedAt
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Must match RequestContext.merchant_id
	Filter        *TransactionFilter     `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	AfterCursor   string                 `protobuf:"bytes,3,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_transaction_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetTransactionsRequest) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetTransactionsRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

func (x *GetTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TransactionSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TransactionId         string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentId             string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ProviderId            string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,4,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Amount                int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_transaction_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_transaction_read_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionSummary) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionSummary) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *TransactionSummary) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *TransactionSummary) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *TransactionSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionSummary) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionSummary  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_transaction_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionsResponse) GetTransactions() []*TransactionSummary {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetTransactionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Must match RequestContext.merchant_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_transaction_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *TransactionSummary    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_transaction_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_read_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionResponse) GetTransaction() *TransactionSummary {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_transaction_read_proto protoreflect.FileDescriptor

const file_transaction_read_proto_rawDesc = "" +
	"\n" +
	"\x16transaction_read.proto\x12\x10transaction_read\"\x98\x01\n" +
	"\x11TransactionFilter\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12&\n" +
	"\x0ffrom_created_at\x18\x03 \x01(\tR\rfromCreatedAt\x12\"\n" +
	"\rto_created_at\x18\x04 \x01(\tR\vtoCreatedAt\"\xaf\x01\n" +
	"\x16GetTransactionsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12;\n" +
	"\x06filter\x18\x02 \x01(\v2#.transaction_read.TransactionFilterR\x06filter\x12!\n" +
	"\fafter_cursor\x18\x03 \x01(\tR\vafterCursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xbd\x02\n" +
	"\x12TransactionSummary\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x126\n" +
	"\x17provider_transaction_id\x18\x04 \x01(\tR\x15providerTransactionId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x9f\x01\n" +
	"\x17GetTransactionsResponse\x12H\n" +
	"\ftransactions\x18\x01 \x03(\v2$.transaction_read.TransactionSummaryR\ftransactions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"_\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\"`\n" +
	"\x16GetTransactionResponse\x12F\n" +
	"\vtransaction\x18\x01 \x01(\v2$.transaction_read.TransactionSummaryR\vtransaction2\xe5\x01\n" +
	"\x16TransactionReadService\x12f\n" +
	"\x0fGetTransactions\x12(.transaction_read.GetTransactionsRequest\x1a).transaction_read.GetTransactionsResponse\x12c\n" +
	"\x0eGetTransaction\x12'.transaction_read.GetTransactionRequest\x1a(.transaction_read.GetTransactionResponseB1Z/payment-gateway/transaction-service/proto;protob\x06proto3"

var (
	file_transaction_read_proto_rawDescOnce sync.Once
	file_transaction_read_proto_rawDescData []byte
)

func file_transaction_read_proto_rawDescGZIP() []byte {
	file_transaction_read_proto_rawDescOnce.Do(func() {
		file_transaction_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_read_proto_rawDesc), len(file_transaction_read_proto_rawDesc)))
	})
	return file_transaction_read_proto_rawDescData
}

var file_transaction_read_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_transaction_read_proto_goTypes = []any{
	(*TransactionFilter)(nil),       // 0: transaction_read.TransactionFilter
	(*GetTransactionsRequest)(nil),  // 1: transaction_read.GetTransactionsRequest
	(*TransactionSummary)(nil),      // 2: transaction_read.TransactionSummary
	(*GetTransactionsResponse)(nil), // 3: transaction_read.GetTransactionsResponse
	(*GetTransactionRequest)(nil),   // 4: transaction_read.GetTransactionRequest
	(*GetTransactionResponse)(nil),  // 5: transaction_read.GetTransactionResponse
}
var file_transaction_read_proto_depIdxs = []int32{
	0, // 0: transaction_read.GetTransactionsRequest.filter:type_name -> transaction_read.TransactionFilter
	2, // 1: transaction_read.GetTransactionsResponse.transactions:type_name -> transaction_read.TransactionSummary
	2, // 2: transaction_read.GetTransactionResponse.transaction:type_name -> transaction_read.TransactionSummary
	1, // 3: transaction_read.TransactionReadService.GetTransactions:input_type -> transaction_read.GetTransactionsRequest
	4, // 4: transaction_read.TransactionReadService.GetTransaction:input_type -> transaction_read.GetTransactionRequest
	3, // 5: transaction_read.TransactionReadService.GetTransactions:output_type -> transaction_read.GetTransactionsResponse
	5, // 6: transaction_read.TransactionReadService.GetTransaction:output_type -> transaction_read.GetTransactionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transaction_read_proto_init() }
func file_transaction_read_proto_init() {
	if File_transaction_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_read_proto_rawDesc), len(file_transaction_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_read_proto_goTypes,
		DependencyIndexes: file_transaction_read_proto_depIdxs,
		MessageInfos:      file_transaction_read_proto_msgTypes,
	}.Build()
	File_transaction_read_proto = out.File
	file_transaction_read_proto_goTypes = nil
	file_transaction_read_proto_depIdxs = nil
}
